### ISSUE TITLE
 DPI setting not working correctly on Logitech G300s

### ISSUE THREAD

**Issue by thalting** [libratbag/libratbag#1458] opened 2023-03-15 14:24 UTC
**Information**
- `ratbagd` version (`ratbagd --version`): 0.17
- Distribution: Arch Linux
- Kernel version (ex. `uname -srmo`): `Linux 6.2.6-zen1-1-zen x86_64 GNU/Linux`

Device info (if applicable):
```
$ ratbagctl <device> info
warbling-mara - Logitech G300s Optical Gaming Mouse
             Model: usb:046d:c246:0
 Number of Buttons: 9
    Number of Leds: 1
Number of Profiles: 3
Profile 0:
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 1000dpi
    1: 1000dpi (active) (default)
    2: 1000dpi
    3: 1000dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to 'resolution-down'
  Button: 6 is mapped to 'resolution-up'
  Button: 7 is mapped to 'profile-cycle-up'
  Button: 8 is mapped to 'resolution-alternate'
  LED: 0, depth: rgb111, mode: on, color: 00ffff
Profile 1: (active)
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 500dpi (active) (default)
    1: 100dpi
    2: 150dpi
    3: 200dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to 'resolution-down'
  Button: 6 is mapped to 'resolution-up'
  Button: 7 is mapped to 'profile-cycle-up'
  Button: 8 is mapped to 'resolution-cycle-up'
  LED: 0, depth: rgb111, mode: on, color: ffffff
Profile 2:
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 200dpi (active) (default)
    1: 400dpi
    2: 600dpi
    3: 0dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to 'resolution-down'
  Button: 6 is mapped to 'resolution-up'
  Button: 7 is mapped to 'profile-cycle-up'
  Button: 8 is mapped to 'resolution-alternate'
  LED: 0, depth: rgb111, mode: on, color: ff00ff
```

**Describe the bug**

**To Reproduce**
`ratbagctl 0 dpi set 2500` set dpi to 2500
`ratbagctl 0 dpi set 500` decrease to 500, and the speed is high than 2500

**Logs**
```
$ ratbagd --verbose=raw

```

**Additional context**
same as  #1216.

**Comment by thalting** [comment] 2023-03-15 14:41
with ratslap (DPI work fine), show different values.

with ratslap:
`
$ ratslap -p f4
RatSlap v0.4.1 (BUILT: 2023-03-15 11:36:39-0300)
Copyright (C) 2016-2020 Todd Harbour
Linux configuration tool for Logitech mice (currently only G300/G300S)
https://gitlab.com/krayon/ratslap/
Found Logitech G300s (046d:c246) @ 0x55d74ae766d0
Detaching kernel driver...
Printing Mode: F4
  Colour:              white
  Report Rate:         1000
  DPI #1:        (DEF) 2000
  DPI #2:              4000
  DPI #3:              1000
  DPI #4:              2000
  DPI Shift:           500 [DISABLED]
  Left Click (But1):   Button1
  Right Click (But2):  Button2
  Middle Click (But3): Button3
  G4:                  Button6
  G5:                  Button7
  G6:                  DPIDown
  G7:                  DPIUp
  G8:                  ModeSwitch
  G9:                  DPICycle
Attaching kernel driver...
`

with ratbagctl
`
Profile 1: (active)
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 400dpi (active) (default)
    1: 800dpi
    2: 1000dpi
    3: 1200dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to 'resolution-down'
  Button: 6 is mapped to 'resolution-up'
  Button: 7 is mapped to 'profile-cycle-up'
  Button: 8 is mapped to 'resolution-cycle-up'
  LED: 0, depth: rgb111, mode: on, color: ffffff
`

**Comment by staticssleever668** [comment] 2023-03-15 16:32
Since you mention it's a duplicate of #1216, let's keep it there.
Thank you for mentioning ratslap though! I have never heard of it before.

**Closed by staticssleever668** 2023-03-15 16:32 UTC
Labels: bug
