### ISSUE TITLE
Logitech G Pro X Superlight not recognised with reciever 046d:c547

### ISSUE THREAD

**Issue by sirris-bat** [libratbag/libratbag#1293] opened 2022-04-10 22:47 UTC
- `ratbagd` version (`ratbagd --version`): 0.16
- Distribution: Arch Linux
- Kernel version (ex. `uname -srmo`): Linux 5.17.1-arch1-1 x86_64 GNU/Linux

$ ratbagctl list
No devices available.

**Describe the bug**
No devices found when using a Logitech G Pro X Superlight (device ID:  046d:c094) + Logitech Unifying Receiver (device ID: 046d:c547)

**To Reproduce**
1. Plug in Unifying receiver
2. Ensure mouse is not plugged in via usb
3. $ ratbagctl list
4. See no devices available

**Additional context**
Current workaround is to plug the mouse in via usb whenever configuration changes are to be made, as ratbagctl can recognise the device in wired mode.

**Comment by idle5** [comment] 2022-04-12 20:33
More information on this issue can be found here:  #1119

**Comment by amfern** [comment] 2022-04-15 23:31
Close as duplicate of #1119

**Closed by amfern** 2022-04-15 23:31 UTC
Labels: bug, kernel
