### ISSUE TITLE
ActiveJet AMY-208 not being detected.

### ISSUE THREAD

**Issue by perrsona1234** [libratbag/libratbag#1082] opened 2020-10-20 20:42 UTC
**Information**

- `ratbagd` version (`ratbagd --version`): 0.15
- Distribution: openSUSE Leap 15.2
- Kernel version (ex. `uname -srmo`): `5.3.18`

Device info (if applicable): N/A

**Describe the bug**
Device cannot be configured. Piper (0.5.1) GUI says that no devices were detected. Sorry, I don't know what else I could put here.

**To Reproduce**
1. Connect the mouse via USB.
2. Open the Piper (0.5.1) GUI.
3. You will see a message that no devices were found.

**Logs**

```
$ ratbagd --verbose=raw
Initializing libratbag
ratbag debug: New device: USB OPTICAL MOUSE 
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 18f8:0f99
ratbag debug: New device: USB OPTICAL MOUSE 
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 18f8:0f99
ratbag debug: New device: SYN1B7F:00 06CB:CD41
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 06cb:cd41
DBus server ready
```

**Additional context**
```
~ ❯❯❯ lsusb
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 004: ID 04ca:3016 Lite-On Technology Corp. 
Bus 003 Device 003: ID 1c7a:0570 LighTuning Technology Inc. 
Bus 003 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 1bcf:2cb0 Sunplus Innovation Technology Inc. 
Bus 001 Device 002: ID 18f8:0f99 [Maxxter] Optical gaming mouse
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

`lsusb` shows the mouse as Maxxter for some reason. Also, the RGB lights on the mouse are constantly cycling through 4 colors (red, blue, pink, purple) and I can't control the via any button on the mouse. It looks like a disco-ball. Sorry, I don't know what kind of info I could give.

Device specification provided by manufacturer: https://productz.com/en/activejet-amy-208/p/3Lbo6

Anyway, thanks for all Your work.

**Comment by perigoso** [comment] 2021-11-04 11:04
duplicate of #615

**Closed by perigoso** 2021-11-04 11:04 UTC
Labels: duplicate, device support
