### ISSUE TITLE
Logitech G700 detected in output but not working

### ISSUE THREAD

**Issue by Draic** [libratbag/libratbag#797] opened 2019-08-13 11:22 UTC
my output from sudo ratbagd --verbose=raw:

ratbag debug: New device: Logitech G700 Laser Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp10
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc06b
ratbag debug: Logitech G700 Laser Mouse is device '/dev/hidraw8'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor

So the mouse is detected but is not working. ratbagctl list still shows: "No devices available."

What am I doing wrong?

**Comment by FFY00** [comment] 2019-08-13 11:27
Start `ratbagd` with `--verbose=raw` and post the output.

**Comment by Draic** [comment] 2019-08-13 11:29
> Start `ratbagd` with `--verbose=raw` and post the output.

I did.
sudo ratbagd --verbose=raw                                                                                                                                   1 ↵  571  13:28
ratbag debug: New device: Draic Ooze
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for feae:8844
ratbag debug: New device: Draic Ooze
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for feae:8844
ratbag debug: New device: Draic Ooze
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for feae:8844
ratbag debug: New device: Logitech G700 Laser Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp10
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc06b
ratbag debug: Logitech G700 Laser Mouse is device '/dev/hidraw8'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142

**Comment by FFY00** [comment] 2019-08-13 11:32
@bentiss is it possible that we are exporting a wrong report descriptor in the kernel driver?

**Comment by bentiss** [comment] 2019-08-13 11:45
hmm, I just re-tested the G700 over USB, and the kernel doesn't even expose the G700 event node. There is something fishy here.

@Draic which kernel are you using?

**Comment by Draic** [comment] 2019-08-13 11:45
Linux 5.2.8-1 on Manjaro

**Comment by bentiss** [comment] 2019-08-13 11:48
@Draic when you say:
> So the mouse is detected but is not working

is it just piper/libratbag that doesn't work or the entire mouse that doesn't control the pointer?

**Comment by Draic** [comment] 2019-08-13 11:49
I can use the mouse like before installing libratbag/piper. Left, Right and Middle button working, but installed libratbag to make use of more buttons. Pointer working aswell ofc

**Comment by bentiss** [comment] 2019-08-13 12:00
K, thanks. Fortunately, the breakage was from a local commit only :)

Investigating further

**Comment by bentiss** [comment] 2019-08-13 12:07
Indeed, that's a kernel bug, you can temporary disable hid-logitech-hidpp (by calling rmmod on it) to be able to remove it, but we should fix this at the kernel level properly

**Comment by Draic** [comment] 2019-08-13 12:15
using rmmod hid-logitech-hidpp indeed works. Now ratbagctl list shows: 
`singing-hare:        Logitech G700 Laser Mouse`

All buttons are working and I can configure the mouse via piper.

**Comment by bentiss** [comment] 2019-08-13 12:22
OK, thanks for confirming. The problem is that we get a timeout when requesting the HID++ version in the kernel. This means we do not create the hidraw node associated with the HID++ collections, and that means libratbag is unable to talk to the device.

The more worrying point is that this prevents the mouse to send keyboards events, thus killing the macros capabilities.

Note: the `rmmod` fix is a temporary one, until we find a proper kernel fix.

**Comment by Draic** [comment] 2019-08-13 12:51
> The more worrying point is that this prevents the mouse to send keyboards events, thus killing the macros capabilities.

Ah this explains a lot. Couple weeks ago a button on the mouse stopped working (mapped to Ctrl+Tab). using `rmmod` immediately gave me back that functionality.

**Comment by bentiss** [comment] 2019-08-13 13:40
I just sent a revert of the G700 support in `hid-logitech-hidpp`: https://patchwork.kernel.org/patch/11092289/

It is marked as stable, and so should be barckported in your distribution relatively rapidly. So the rmmod hack will not be required "soon"

**Comment by Pshemas** [comment] 2019-08-18 21:07
can't set up my g700s as well. Tried rmmod but didn't help - I still can't assign keys to the device.
Ratbactl detects the device and I can get the info:

ratbagctl "Logitech G700s Rechargeable Gaming Mouse" info
screaming-chipmunk - Logitech G700s Rechargeable Gaming Mouse
             Model: usb:046d:c07c:0
 Number of Buttons: 13
    Number of Leds: 0
Number of Profiles: 5
Profile 0: (active)
  Name: Profil 1
  Report Rate: 125Hz
  Resolutions:
    0: 200x200dpi
    1: 1200x1200dpi
    2: 2300x2300dpi (active)
    3: 3300x3300dpi
    4: <disabled>
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to UNKNOWN
  Button: 4 is mapped to UNKNOWN
  Button: 5 is mapped to UNKNOWN
  Button: 6 is mapped to 'button 4'
  Button: 7 is mapped to UNKNOWN
  Button: 8 is mapped to UNKNOWN
  Button: 9 is mapped to UNKNOWN
  Button: 10 is mapped to 'resolution-cycle-up'
  Button: 11 is mapped to 'wheel-left'
  Button: 12 is mapped to 'wheel-right'
Profile 1: (disabled)
Profile 2: (disabled)
Profile 3: (disabled)
Profile 4: (disabled)

- but it is wrong as it does not show keys mapped (for example one of the buttons works as "del").
Any ideas how can I make it work?
I've tried reassigning the keys with Piper, but when I hit apply I get "something went wrong"/

**Comment by FFY00** [comment] 2019-08-18 21:23
Please wait for the mentioned patch to get deployed.

**Comment by Pshemas** [comment] 2019-08-18 21:34
ok, I will. But I'm just wondering - Draic mentioned that with rrmod it was possible to configure the g700s mice. On my end it is not working - so I worry it might be another issue. I can view the device, but can't assign buttons.

**Comment by Pshemas** [comment] 2019-08-18 21:53
and just in case here you'll find output of  ratbagd --verbose=raw when g700s is connected via usb (and did rmmod before):
https://paste.fedoraproject.org/paste/vzpdVUMASEUSk2LwrbwI2w

**Comment by Draic** [comment] 2019-08-19 06:05
your case is definitely different to mine, as the mouse is recognized by ratbagd and it is not the same mouse in the first place. G700 vs G700s which are not identical.

Once my G700 got recognized, I could change button assignments. No error message like you described. Can't help you, sorry, but our problems do not seem to be related

**Comment by FFY00** [comment] 2019-08-19 06:10
@Pshemas you can't assign keys or the keys that you assigned in Windows don/t work on Linux?

**Comment by Pshemas** [comment] 2019-08-19 19:18
@FFY00 can't assign keys. Things set up using Logitech software on Windows work correctly on Linux.

**Comment by FFY00** [comment] 2019-08-19 19:36
Ok, I am not really up to date with the state of the hidpp10 driver but I guess that might be expected.

**Comment by YoyPa** [comment] 2019-08-20 02:52
Hello,
I've reported 2weeks ago similar issue on kernel.org:
https://bugzilla.kernel.org/show_bug.cgi?id=204519
Should I close it ?

I've also seen a user complaining about "a really similar" issue on a G900:
https://forum.manjaro.org/t/logitech-g900-mouse-side-buttons-not-working-in-kernel-5-2-2-1/96511

**Comment by Evils-Devils** [comment] 2019-09-09 05:15
Hi, not a libratbag user (yet, just found out about it).
I'd like to thank @bentiss for addressing a kernel issue so fast, their fix got backported to 5.2.11 along with the commit that introduced it.
It seems my G700s is also affected, @pshemas, i recommend you stay away from 5.2.11 and later until [this](https://github.com/torvalds/linux/commit/addf3382c47c033e579c9c88f18e36c4e75d806a) commit is available to you (5.3 unless it also gets backported).

**Comment by FFY00** [comment] 2019-09-26 07:57
Can you confirm this is working in Linux 5.3?

**Comment by Draic** [comment] 2019-09-26 08:59
yes, I just tried out 5.3 and indeed my G700 worked correctly right after boot.

**Closed** 2019-09-26 08:59 UTC
Labels: bug, device-specific

**Comment by calvertdw** [comment] 2020-01-07 17:59
I am on Linux 5.4.8-arch1-1 amd64 and having this issue.

```
$ ratbagctl warbling-mara info
warbling-mara - Logitech G700s Rechargeable Gaming Mouse
             Model: usb:046d:c07c:0
 Number of Buttons: 13
    Number of Leds: 0
Number of Profiles: 5
Profile 0: (active)
  Name: Work Default
  Report Rate: 1000Hz
  Resolutions:
    0: 2100x2100dpi (active)
    1: <disabled>
    2: <disabled>
    3: <disabled>
    4: <disabled>
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to UNKNOWN
  Button: 6 is mapped to UNKNOWN
  Button: 7 is mapped to 'button 5'
  Button: 8 is mapped to 'button 4'
  Button: 9 is mapped to UNKNOWN
  Button: 10 is mapped to UNKNOWN
  Button: 11 is mapped to 'button 4'
  Button: 12 is mapped to 'button 5'
Profile 1: (disabled)
Profile 2: (disabled)
Profile 3: (disabled)
Profile 4: (disabled)
```
