### ISSUE TITLE
When using any macro function of the mouse at a drop of fps

### ISSUE THREAD

**Issue by Mobilizar** [libratbag/libratbag#916] opened 2020-02-03 00:52 UTC
**Information**

- `ratbagd` version (`ratbagd --version`): 0.12
- Distribution: 
- Kernel version (ex. `uname -srmo`): Linux 5.3.0-28-generic x86_64 GNU/Linux

**Describe the bug**
I have a G600 mouse, au set up macro functions to trigger F1 for example, to a peak of processing that ends up having a significant drop of FPS reaching to lock the screen for a few seconds. After the initial slowness the action is carried out successfully. I wonder if there is any way to run the macro without dropping fps?

**Comment by marciodojr** [comment] 2020-03-10 21:46
Same problem here with my Logitech G600

- ratbagd version (ratbagd --version): 0.13
- Distribution: Ubuntu 19.10
- Kernel Version: Linux 5.3.0-40-generic x86_64 GNU/Linux

I don't know if it helps but I have exactly the same problem (high CPU usage when using special buttons) with a not supported mouse [Multilaser Warrior 218](https://suporte.multilaser.com.br/produtos/mouse-profissional-8-botoes-2500-dpi-preto-com-led-usb-mo218).

**Comment by FFY00** [comment] 2020-04-13 01:19
I can't reproduce on any of my devices and I don't think this bug belongs to libratbag. Closing. If you manage to get information pointing otherwise feel free to reopen.

**Closed by FFY00** 2020-04-13 01:19 UTC
Labels: bug
