### ISSUE TITLE
Request: MX Master 2S support

### ISSUE THREAD

**Issue by codedcosmos** [libratbag/libratbag#511] opened 2018-08-19 08:21 UTC
Hi, I recently got myself a MX master 2s, and so far it has worked quite well. However I would like to configure it a little more. I found this project and it looks promising, however my device is not currently supported by the software.

I'm very willing to help, and would even be willing to "reverse engineer it" however I have not tried something like that before (closest to it would be nes home-brewing), but think it would be fun to learn, so some pointers would be appreciated.

**Comment by FFY00** [comment] 2018-08-19 09:06
Well, the process is just identify the device i. Wireshark, send some commands using the official driver and then trying to figure out what each packet is.

**Comment by codedcosmos** [comment] 2018-08-20 05:53
Alright, I will try to make sense of all the packets, Will reply back here once I figured them all out.

**Comment by FFY00** [comment] 2018-08-20 12:32
You don't need to do that alone. You're welcome to post the packet dumps here and we'll help you out :smile:.

**Comment by dcelasun** [comment] 2018-08-21 15:45
Duplicate of #419.

**Comment by FFY00** [comment] 2018-08-21 15:48
@dcelasun thank you, didn't notice. @codedcosmos please use #419 to report your findings or ask for help :blush:.

**Closed by FFY00** 2018-08-21 15:48 UTC
