### ISSUE TITLE
Logitech M705 is not detected

### ISSUE THREAD

**Issue by dandarie** [libratbag/libratbag#720] opened 2019-06-28 00:00 UTC
My Logitech M705 is not detected. The device match string seems to be different.

Here is the  ratbagd --verbose=raw output:

ratbag debug: New device: Logitech M510
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:1025
ratbag debug: New device: Logitech M705
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for **046d:406d**
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c52b

---
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.04
DISTRIB_CODENAME=disco
DISTRIB_DESCRIPTION="Ubuntu 19.04"
Linux a2 5.0.0-19-generic

Piper is installed from the Ubuntu PPA.
piper/disco,now 0.2.904-201906201417\~ubuntu19.04.1 amd64
ratbagd/disco,now 0.9.905-1-201906170431\~ubuntu19.04.1 amd64

I'm using Gnome 3.32.

**Comment by FFY00** [comment] 2019-06-28 01:43
Looks like the data file is missing that ID, could you add it and try again?

**Comment by FFY00** [comment] 2019-07-02 12:41
Are you talking about the "Logitech M705" orthe "Loitech Marathon M705"?

**Comment by whot** [comment] 2019-07-23 04:03
Silence, so let's close this, maybe it was fixed with #726 anyway

**Comment by FFY00** [comment] 2019-07-23 05:36
Different mice

**Comment by FFY00** [comment] 2019-08-14 13:04
I tested this and the mouse is working, please reopen if you can't reproduce.

**Closed by FFY00** 2019-08-14 13:04 UTC
