### ISSUE TITLE
Add Glorious Model I Support

### ISSUE THREAD

**Issue by secretknowledge** [libratbag/libratbag#1567] opened 2023-12-14 16:11 UTC
Recently I have been attempting to get my Glorious Model I setup under Linux. I changed the denounce time via a USB passthrough and libinput overrides, but rebinding keys did not work.

If someone could add a device file so I could use it in Piper that would be awesome.

I attempted to use input remapper and checked input events but it didn't get detected. Rebinding via a USB passthrough only worked on a VM.

Thank you!

**Comment by staticssleever668** [comment] 2023-12-15 15:49
Model I would require a new driver for libratbag, PRs welcome.
Duplicate of #1327.

**Closed by staticssleever668** 2023-12-15 15:49 UTC
Labels: enhancement
