### ISSUE TITLE
glorious model O showing wrong dpi list

### ISSUE THREAD

**Issue by Alib234** [libratbag/libratbag#1476] opened 2023-04-22 21:19 UTC
**Information**
- `ratbagd` version (`ratbagd --version`): 0.17
- Distribution: Arch
- Kernel version (ex. `uname -srmo`): Linux 6.2.10-273-tkg-pds x86_64 GNU/Linux

dpi shows from 0 to 2000, while it should show from 0 to 12000 for the model O, this was the case in past versions of libratbag, idk for how many versions this was wrong

**Comment by staticssleever668** [comment] 2023-04-23 15:09
Thanks for reporting! I think this is a regression since v0.16 in v0.17. I noticed this recently and fixed in f96c5e24.

**Closed by staticssleever668** 2023-04-23 15:09 UTC
Labels: bug

**Comment by Alib234** [comment] 2023-09-28 17:08
I'm going to have to unfortunately re-open this issue as I have noticed it is happening again
