### ISSUE TITLE
Logitech G203 Issue

### ISSUE THREAD

**Issue by BobbyJackT** [libratbag/libratbag#1057] opened 2020-09-11 20:57 UTC
I recently got the new color variant of the Logitech G203 mouse in lilac. I was excited to be able to control the mouse lighting and features on Linux. I checked the support page for supported mice and I saw the G103/203 were supported in a section together. The error I am getting is that there is no supported mouse plugged in. I tried unplugging and replugging the mouse as well as restarting my computer. The mouse works fine functionality wise besides not showing as supported.

**Comment by perigoso** [comment] 2020-09-11 22:12
You should consider closing #1056, no need to create duplicates.

**Comment by staticssleever668** [comment] 2023-03-24 12:58
1:1 duplicate of #1056.

**Closed by staticssleever668** 2023-03-24 12:58 UTC
Labels: bug, duplicate
