### ISSUE TITLE
Logitech M705 segfault "invalid number of profiles (0)"

### ISSUE THREAD

**Issue by KlfJoat** [libratbag/libratbag#970] opened 2020-04-29 01:31 UTC
**Information**
- `ratbagd` version (`ratbagd --version`):  0.13
- Distribution:  Ubuntu 20.04
- Kernel version (ex. `uname -srmo`): `Linux 5.4.0-26-generic x86_64 GNU/Linux`

**Describe the bug**
Starting Piper did not work, so I tried `ratbagctl list` to troubleshoot. That gave me an error connecting to `ratbagd`, so I tried running it and saw the segfault. 

**To Reproduce**
1. Run `sudo /usr/bin/ratbagd --verbose`
2. See segfault

**Logs**
```
$ ratbagd --verbose=raw
Initializing libratbag
ratbag debug: New device: Kingston HyperX Cloud Flight Wireless Headset
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 0951:16c4
ratbag debug: New device: Arduino LLC iWit USB Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 2341:484d
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Valve Software Steam Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 28de:1142
ratbag debug: New device: Cooler Master Technology Inc. CK530
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 2516:009f
ratbag debug: New device: Cooler Master Technology Inc. CK530
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 2516:009f
ratbag debug: New device: Cooler Master Technology Inc. CK530
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 2516:009f
ratbag debug: New device: Logitech M705
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp10
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0x101b
ratbag debug: Logitech M705 is device '/dev/hidraw17'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: - HID report ID 20
ratbag debug: - HID report ID 21
ratbag raw: Fetching individual features (0x1)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 01 | 00 00 00
ratbag raw: hidpp write:  10 00 81 01 00 00 00
ratbag raw: hidpp read:   10 02 81 01 02 00 00
ratbag raw: hidpp10 rx:  10 | 00 | 81 | 01 | 02 00 00
ratbag raw: Fetching HID++ notifications (00)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 00 | 00 00 00
ratbag raw: hidpp write:  10 00 81 00 00 00 00
ratbag raw: hidpp read:   10 02 81 00 10 00 00
ratbag raw: hidpp10 rx:  10 | 00 | 81 | 00 | 10 00 00
ratbag raw: Fetching current resolution (0x63)
ratbag raw: hidpp10 tx:  10 | 00 | 83 | 63 | 00 00 00
ratbag raw: hidpp write:  10 00 83 63 00 00 00
ratbag raw: hidpp read:   10 02 8f 83 63 01 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_SUBID (01)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 83 | 63 01 00
ratbag raw: Fetching LED status (0x51)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 51 | 00 00 00
ratbag raw: hidpp write:  10 00 81 51 00 00 00
ratbag raw: hidpp read:   10 02 8f 81 51 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 51 02 00
ratbag raw: Fetching USB refresh rate (0x64)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 64 | 00 00 00
ratbag raw: hidpp write:  10 00 81 64 00 00 00
ratbag raw: hidpp read:   10 02 8f 81 64 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 64 02 00
ratbag raw: Fetching optical sensor settings (0x61)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 61 | 00 00 00
ratbag raw: hidpp write:  10 00 81 61 00 00 00
ratbag raw: hidpp read:   10 02 8f 81 61 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 61 02 00
ratbag raw: Fetching current profile (0xf)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 0f | 00 00 00
ratbag raw: hidpp write:  10 00 81 0f 00 00 00
ratbag raw: hidpp read:   10 02 8f 81 0f 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 0f 02 00
ratbag error: Failed to get HID++1.0 device for Logitech M705
ratbag error: libratbag bug: Logitech M705: invalid number of profiles (0)
Segmentation fault
```
That output exits with an error code 139.

**Additional context**

I know that this is the second mouse I have attached to this Unifying Receiver.  And I saw another libratbag bug where missing/powered off devices in Unifying slots could be a problem. So I opened Solaar to check.  I only have the one mouse paired with this Unifying Receiver, but it is in the second slot. Maybe that has something to do with this error?

```
$ /usr/bin/solaar --debug show
Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c52b
  Serial       : 40019EE7
    Firmware   : 12.07.B0029
    Bootloader : 02.15
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 2=176
20:19:17,332    ERROR [MainThread] logitech_receiver.receiver: failed to read Nano wpid for device 1 of <UnifyingReceiver(/dev/hidraw1,3)>
20:19:17,332    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 415, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
logitech_receiver.base.NoSuchDevice: {'number': 1, 'receiver': <UnifyingReceiver(/dev/hidraw1,3)>, 'error': 'read Nano wpid'}
20:19:17,339  WARNING [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,3)>: looked for device 1, not found
20:19:17,340     INFO [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,3)>: found new device 2 (101B)

  2: Marathon Mouse M705 (M-R0009)
     Codename     : M705 (M-R0009)
     Kind         : mouse
     Wireless PID : 101B
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: 8CEE273D
          Firmware: 17.01.B0017
        Bootloader: 02.06
             Other: 00.04
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Battery: 75%, discharging.
```

**Comment by FFY00** [comment] 2020-04-29 01:48
Duplicate of #942

**Closed by FFY00** 2020-04-29 01:48 UTC
Labels: bug, duplicate

**Comment by KlfJoat** [comment] 2020-04-29 02:05
@FFY00 
I think you maybe closed this as a duplicate accidentally?

In #942, the person once had a M705 connected, the device is now turned off, but the Unifying Receiver still has it in a slot.

I currently have a M705 connected, the device is turned on, and it is the only thing in any slot on my Unifying Receiver.

Also in #942, you mention that `libratbag` gets a `ERR_RESOURCE_ERROR` when trying to talk to the slot with the non-connected device.  My output shows no `ERR_RESOURCE_ERROR` at all.

**Comment by FFY00** [comment] 2020-04-29 02:09
When the device is online you get a segfault, when it is offline you hit #785.

The pairing history on your receiver doesn't influence anything here :D

**Comment by KlfJoat** [comment] 2020-04-29 02:37
Okay.  Well, I DID review #942, and it didn't seem like it reflected my issue.  Still doesn't.  But I defer to you as the developer.

So, looking at #954, is that the fix?  Should I try installing from the daily PPA to test?

**Comment by FFY00** [comment] 2020-04-29 13:43
Yes, please test it.

**Comment by KlfJoat** [comment] 2020-04-30 01:38
YAY!  No more `ratbagd` segfault!  

BOO!  Now `piper` doesn't start!  Time to look over there for Issues.  

Thanks for your help!

**Comment by FFY00** [comment] 2020-04-30 01:50
Yes, please investigate and report back.
