### ISSUE TITLE
Add M585/M590 support

### ISSUE THREAD

**Issue by s8321414** [libratbag/libratbag#831] opened 2019-10-24 04:08 UTC
Please add M585/M590 support, what information should I provide to do this?

**Comment by FFY00** [comment] 2019-11-17 14:41
You can create a .device file and see if the mouse works.

It should be:
```
[Device]
Name=Logitech M590
DeviceMatch=usb:046d:ID-HERE
Driver=hidpp20
```

To find the ID please do `dmesg | grep logitech`, you should see something like:
```
logitech-hidpp-device 0003:046D:407B.0044: HID++ 4.5 device connected.
```
Here `407B` is the ID of my device.

**Comment by s8321414** [comment] 2019-11-17 23:42
So I should make a PR or I can just them here?

**Comment by s8321414** [comment] 2019-11-17 23:43
And M585/M590 should share same hardware except normal/silent click.

**Comment by FFY00** [comment] 2019-11-17 23:48
If it is working please open a pull request.

**Comment by s8321414** [comment] 2019-11-17 23:50
OK, and dmesg shows M585/M590 in message, how can I do for this?

**Comment by FFY00** [comment] 2019-11-18 01:06
Sorry? What do you mean? The ID should be located where marked by `XXXX` in `0003:046D:XXXX`.

**Comment by s8321414** [comment] 2019-11-18 02:10
I can see three logitch related device on my computer:
```
logitech-djreceiver 0003:046D:C52B.0003: hiddev0,hidraw0: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:00:1d.0-1.1/input2
logitech-hidpp-device 0003:046D:406B.0004: input,hidraw1: USB HID v1.11 Keyboard [Logitech M585/M590] on usb-0000:00:1d.0-1.1/input2:1
logitech-hidpp-device 0003:046D:406B.0004: HID++ 4.5 device connected.
```
So I just need last one to create device file right? But what device name should I fill?

**Comment by FFY00** [comment] 2019-11-18 14:41
Yes, you can put `Logitech M585/M590`.

**Comment by AlexP11223** [comment] 2020-07-17 19:41
Any progress? Planning to buy this mouse soon :)

**Comment by s8321414** [comment] 2020-07-20 06:40
> Any progress? Planning to buy this mouse soon :)

I added initial support to libratbag, but no image (.svg) can be used in piper.

**Comment by AlexP11223** [comment] 2020-07-20 10:16
ah, yeah https://github.com/libratbag/libratbag/pull/845


> but no image (.svg) can be used in piper.

hm, what image? Do you mean just image of the mouse? So it just displays some generic mouse image? Shouldn't be a problem then.

**Comment by s8321414** [comment] 2020-07-21 06:56
> hm, what image? Do you mean just image of the mouse? So it just displays some generic mouse image? Shouldn't be a problem then.

https://github.com/libratbag/piper/tree/master/data/svgs
Yeah, piper will show generic mouse image.

**Comment by zilexa** [comment] 2020-11-28 15:52
Just using an old open ticket instead of creating a new one: Logitech M590 connected via Bluetooth:

```
$ ratbagctl list
singing-gundi:       M585/M590 
```

```
$ ratbagctl M585/M590 info
singing-gundi - M585/M590
             Model: bluetooth:046d:b01b:0
 Number of Buttons: 8
    Number of Leds: 0
Number of Profiles: 1
Profile 0: (active)
  Name: n/a
  Report Rate: 0Hz
  Resolutions:
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to 'wheel-left'
  Button: 6 is mapped to 'wheel-right'
  Button: 7 is mapped to UNKNOWN
```

dmesg shows: 
```
[43606.943522] input: M585/M590 Keyboard as /devices/virtual/misc/uhid/0005:046D:B01B.0003/input/input18
[43606.943758] input: M585/M590 Mouse as /devices/virtual/misc/uhid/0005:046D:B01B.0003/input/input19
[43606.944709] hid-generic 0005:046D:B01B.0003: input,hidraw1: BLUETOOTH HID v0.11 Keyboard [M585/M590] on 6c:6a:77:3d:03:c8
[43645.455573] input: M585/M590 Keyboard as /devices/virtual/misc/uhid/0005:046D:B01B.0004/input/input21
[43645.456355] input: M585/M590 Mouse as /devices/virtual/misc/uhid/0005:046D:B01B.0004/input/input22
[43645.456721] hid-generic 0005:046D:B01B.0004: input,hidraw1: BLUETOOTH HID v0.11 Keyboard [M585/M590] on 6c:6a:77:3d:03:c8
```

In Piper I only see Buttons overview, nothing else. I am missing Resolution, Sensitivity.

**Comment by Mr-Crabman** [comment] 2021-12-25 16:41
I second the problem @zilexa has, the info looks like this for me:
```
$ ratbagctl M585/M590 info
thundering-gerbil - Logitech M585/M590
             Model: usb:046d:406b:0
 Number of Buttons: 8
    Number of Leds: 0
Number of Profiles: 1
Profile 0: (active)
  Name: n/a
  Report Rate: 0Hz
  Resolutions:
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to 'wheel-left'
  Button: 6 is mapped to 'wheel-right'
  Button: 7 is mapped to UNKNOWN
```

Also, binding macros/sending keystrokes (in Piper) doesn't work at all, for any of the buttons or keys.

And finally, the mouse seems to forget any settings I change on it after a few minutes of not doing anything with the mouse (I'm guessing it's caused by auto-sleep).

**Comment by staticssleever668** [comment] 2023-03-08 12:36
Fixed by https://github.com/libratbag/libratbag/pull/845

> Just using an old open ticket instead of creating a new one: Logitech M590 connected via Bluetooth:

This is really old, but if this is still a problem, please, open a new issue.

**Closed by staticssleever668** 2023-03-08 12:36 UTC
Labels: enhancement, device specific
