### ISSUE TITLE
Steam Deck libratbag is not in flatpak format, and is not easy to install for Linux newcomer

### ISSUE THREAD

**Issue by MadogPL** [libratbag/libratbag#1401] opened 2022-12-30 12:49 UTC
Hallo

Steam Deck allows to install Piper, but Piper requires libratbag to operate, and it's not available in flatpak "Discover" program.
Steam warns that even if I unlock all the functionalities of the deck (sudo, pacman, whatever that means), It might get overwritten in next system update. 

Make instruction how to install those things safely on Steam Deck or make the libratbag avaliable with flatpak to install.

Each step I take is showing me warning signs that I cannot this, cannot that, I'm not root, not admin, not allowed sudo, does not have admin, and even if I do all this, the system update will overwrite this :/

**Comment by staticssleever668** [comment] 2022-12-30 17:23
Hi, sorry, but think it's probably impossible to package libratbag in Flatpak format, as it requires direct access to configured devices. For this reason ratbagd runs with root rights. It's possible to make such an application to work without root by adjusting udev rules, but it still requires root access at first.
If you know any device configuration utilities that do work with flatpak, please, tell me.

Regarding Steam Deck support: honestly, I think distro-specific (SteamOS in this case) installation is out of scope of the project.
However, I think it's possible for anyone to modify [the wiki of the project](https://github.com/libratbag/libratbag/wiki/Installation), where we do have some installation information. If anyone has already installed libratbag on Steam OS successfully, they are free to share with other people how they did it.

**Closed by staticssleever668** 2022-12-30 17:23 UTC
Labels: enhancement

**Comment by Commenter25** [comment] 2026-05-17 05:38
Hi! I know this is an old issue, I had this problem as well and found it...

> If you know any device configuration utilities that do work with flatpak, please, tell me.

Perhaps you could copy [what the LACT developers have done](https://github.com/ilya-zlobintsev/LACT/tree/master/flatpak#implementation-details)? They made a tool called [Flatbox](https://github.com/ilya-zlobintsev/flatbox), which allows running privileged processes within a separate sandbox, while the regular application (in this case, Piper) stays in the minimally-privileged Flatpak sandbox. Flatbox still uses the Flatpak runtime for broad compatibility, yet has little restriction on host system access, including `/dev` (which I believe the issue here is needing `/dev/hidraw`?)

Normally, such a sandbox escape would not be permitted on Flathub, but there is an [explicit exception](https://docs.flathub.org/docs/for-app-authors/requirements#submissions-incompatible-or-restricted-by-flatpak-sandbox) for implementations by the upstream developers of an application, which is how LACT was accepted. And in this case, perhaps libratbag's environment could be tightened to remain reasonably sandboxed, since libratbag's needs are much less broad. Piper's permissions could also be very minimal, [as seen with LACT](https://github.com/flathub/io.github.ilya_zlobintsev.LACT/blob/master/io.github.ilya_zlobintsev.LACT.yaml#L9); with the only dangerous permission being `org.freedesktop.Flatpak`, which can be safely revoked after initial setup installs the daemon.

cc @ilya-zlobintsev in case you'd like to give insights

As a side note, this wouldn't exclusively be a benefit for SteamOS. Besides regular distros which simply don't have libratbag packages, [atomic distros](https://fedoraproject.org/atomic-desktops/) are becoming very popular, especially [Bazzite](https://bazzite.gg/). It is possible to layer packages on these distros, but that comes with a number of downsides, including slower updates, required reboots, and degrading the reproducibility and stability that atomic systems provide. Additionally, an [upcoming verified boot chain](https://planet.kde.org/siosms-blog-2026-04-27-sealed-fedora-atomic-desktop-bootable-container-images/) would be incompatible with layering, so users would have to lose out on a massive security improvement.

**Comment by ilya-zlobintsev** [comment] 2026-05-17 06:13
> Hi! I know this is an old issue, I had this problem as well and found it...
> 
> > If you know any device configuration utilities that do work with flatpak, please, tell me.
> 
> Perhaps you could copy [what the LACT developers have done](https://github.com/ilya-zlobintsev/LACT/tree/master/flatpak#implementation-details)? They made a tool called [Flatbox](https://github.com/ilya-zlobintsev/flatbox), which allows running privileged processes within a separate sandbox, while the regular application (in this case, Piper) stays in the minimally-privileged Flatpak sandbox. Flatbox still uses the Flatpak runtime for broad compatibility, yet has little restriction on host system access, including `/dev` (which I believe the issue here is needing `/dev/hidraw`?)
> 
> Normally, such a sandbox escape would not be permitted on Flathub, but there is an [explicit exception](https://docs.flathub.org/docs/for-app-authors/requirements#submissions-incompatible-or-restricted-by-flatpak-sandbox) for implementations by the upstream developers of an application, which is how LACT was accepted. And in this case, perhaps libratbag's environment could be tightened to remain reasonably sandboxed, since libratbag's needs are much less broad. Piper's permissions could also be very minimal, [as seen with LACT](https://github.com/flathub/io.github.ilya_zlobintsev.LACT/blob/master/io.github.ilya_zlobintsev.LACT.yaml#L9); with the only dangerous permission being `org.freedesktop.Flatpak`, which can be safely revoked after initial setup installs the daemon.
> 
> cc [@ilya-zlobintsev](https://github.com/ilya-zlobintsev) in case you'd like to give insights
> 
> As a side note, this wouldn't exclusively be a benefit for SteamOS. Besides regular distros which simply don't have libratbag packages, [atomic distros](https://fedoraproject.org/atomic-desktops/) are becoming very popular, especially [Bazzite](https://bazzite.gg/). It is possible to layer packages on these distros, but that comes with a number of downsides, including slower updates, required reboots, and degrading the reproducibility and stability that atomic systems provide. Additionally, an [upcoming verified boot chain](https://planet.kde.org/siosms-blog-2026-04-27-sealed-fedora-atomic-desktop-bootable-container-images/) would be incompatible with layering, so users would have to lose out on a massive security improvement.

Flathub generally allows sandbox escapes if they are required for the application to be usable.

The reason LACT needs flatbox is that it has some runtime dependencies, and cannot be linked statically due to interaction with certain drivers. If you can build your service part as a fully static binary, that would be the easiest way, as then you can just spawn it on the host directly. [GPU screen recorder](https://flathub.org/en/apps/com.dec05eba.gpu_screen_recorder) takes this approach. 

The whole escape is a bit hacky, and sometimes there are still distro things you have to care about (for example, some SELinux/AppArmor setups don't allow binaries from flatpak installation paths to be executed directly by default), so it is understandable if the maintainers do not want to bother with this. But as mentioned, the app distribution benefit may be worth it.
