### ISSUE TITLE
G703 Resolution Management

### ISSUE THREAD

**Issue by DarkArc** [libratbag/libratbag#604] opened 2019-01-19 19:33 UTC
Piper is showing the add resolution and remove resolution options, and based on what I've read it seems the mouse should support up to 5 different resolutions -- but not require 5. 

However, neither the add, nor remove buttons do anything. I initially saw that the 5th profile was "0" which seemed to be a disabled state, but cannot set it back to 0, lowest I can set it to is 50. 

If this is a piper issue, please let me know and I'll gladly report over to them; or if there's a good way to verify which side has the problem, please let me know that as well.

**Comment by Hjdskes** [comment] 2019-01-21 14:52
> Piper is showing the add resolution and remove resolution options ... However, neither the add, nor remove buttons do anything

These were placeholders that we intended to implement, but we never got around to doing this. If you try the latest git master of Piper, you'll see that the add resolution button is gone. We still need to remove the delete buttons.

> I initially saw that the 5th profile was "0" which seemed to be a disabled state, but cannot set it back to 0, lowest I can set it to is 50.

I'm not sure if there's a technical reason for this, but we're tracking it in https://github.com/libratbag/piper/issues/266. This issue is a duplicate of that one, so I'm closing this.

**Closed by Hjdskes** 2019-01-21 14:52 UTC
