### ISSUE TITLE
Logitech G502 Proteus Core ERR_INVALID_ADDRESS

### ISSUE THREAD

**Issue by PlasmaPower** [libratbag/libratbag#280] opened 2017-08-14 22:28 UTC
Whenever I try to "apply" in piper, it says "Failed to commit changes". I also get this error from ratbagd: `ratbag error:     HID++ error from the device (255): ERR_INVALID_ADDRESS (02)`

May be related to #24, not sure.

**Comment by PlasmaPower** [comment] 2017-08-15 00:18
Not sure if this is related, but it seems the LED capabilities are also incorrectly detected.

**Comment by cvuchener** [comment] 2017-08-15 08:15
Which version are using (v0.9 or latest git)?

Can you reproduce the issue with ratbag-command? If you do, post the output using the `--verbose=raw` option.

> Not sure if this is related, but it seems the LED capabilities are also incorrectly detected.

How exactly are they incorrectly detected? libratbag's logitech driver only support RGB LED effects. It is expected if no LED capabilities are reported.

**Comment by PlasmaPower** [comment] 2017-08-15 17:11
@cvuchener I'm using latest git. I get the same error with ratbag-command. Here's the output of `sudo ./ratbag-command --verbose=raw button 5 action set button 6 /dev/input/event4`: https://gist.github.com/PlasmaPower/4beaea7976caf169ffd92dabbf5cd2c9

Two LEDs are detected, but I don't believe either are configurable, and I certainly don't think either are RGB. I think that's only in the spectrum version of the mouse. I only have the core version.

**Comment by cvuchener** [comment] 2017-08-16 08:16
I don't know why there is a "invalid address" error. The writing looks good to me. But the profile data seems to be corrupted: all profiles are disabled and profiles data is offset by 16 bytes. Did libratbag do that? Did you modify the profiles in another way before?

**Comment by PlasmaPower** [comment] 2017-08-16 17:47
@cvuchener I've never modified this mouse before now. The profiles are all stock (and they work fine). Libratbag only showed the currently enabled profile, and I didn't try to add a new profile or anything likke that. Maybe I should use the official Windows tool first, to setup the profiles?

**Comment by amfern** [comment] 2017-08-16 20:47
i tested it on same mouse type g502 without RGB feature too, and it worked.
`sudo ./ratbag-command --verbose=raw button 5 action set button 6 /dev/input/event2:`
https://gist.github.com/amfern/aac977f1da47916b60e742f15e96952e

**Comment by PlasmaPower** [comment] 2017-08-16 21:05
Interesting. @amfern Have you setup your profiles with the Windows tool?

**Comment by amfern** [comment] 2017-08-16 22:25
yes the profiles were changed from windows with logitech drivers before i tried with libratbag

**Comment by PlasmaPower** [comment] 2017-08-16 22:30
Should I do any sort of USB interception while initiallty setting up the profiles? It may be helpful to future users with the same problem.

**Comment by amfern** [comment] 2017-08-16 22:53
yes, i used windows vm and recorded the traffic with wireshark from linux host.
i am not aware of any setup process for the mouse, but maybe on first connect to logitech driver something happens or maybe on first profile save.

it would really help if you try and tell us about your results, even without the USB interception.

**Comment by PlasmaPower** [comment] 2017-08-17 00:09
I think clicking the check marks next to the profiles in the Windows UI fixed it. Here's the pcap: https://drive.google.com/file/d/0B9G6d3O57cmAVUZmeUhsaUF2ckk/view?usp=sharing

**Comment by amfern** [comment] 2017-08-17 05:18
maybe non of the profiles was enabled or maybe there was no active profiles, wish we could go back in time and run `ratbag-command info` on the device :).

i will try to get the same error by to disable all the profiles and removing the active.

**Comment by PlasmaPower** [comment] 2017-08-17 07:19
@amfern I'm pretty sure none of the profiles were enabled, though I could switch through them fine with the profile switch button on my mouse.

**Comment by PlasmaPower** [comment] 2017-08-17 07:20
There was definitely an active profile that libratbag could detect. Though I couldn't switch profiles with the UI, if I switched profiles with the mouse then restarted ratbagd, libratbag saw that the profile changed.

**Comment by cvuchener** [comment] 2017-08-17 08:39
If I write a list of all-disabled profiles, on my G502 spectrum, I get the same error. Although, it should be an "invalid argument" error, libratbag is confusing HID++1.0 and HID++2.0 error codes.

> Libratbag only showed the currently enabled profile

ratbag-command should not have shown any profile as "enabled". This is what I get after overwriting my profile list with disabled profiles (and receiving the error):

```
Device 'Logitech Gaming Mouse G502'
Capabilities: res profile btn-key led
Number of buttons: 11
Number of leds: 2
Profiles supported: 3
  Profile 0 (disabled)
  Profile 1 (disabled) (active)
  Profile 2 (disabled)
```

> I could switch through them fine with the profile switch button on my mouse.

When the firmware detect any invalid data, it uses profiles from the ROM, so the mouse is still usable and seems to work with its factory default profiles.

**Comment by cvuchener** [comment] 2017-08-18 09:31
I have been testing a few broken profiles, and I don't think the hidpp20 driver is behaving appropriately.

When the driver detects an error, it defaults to the ROM profile *individually*. But, from my observation of my G502 spectrum, it is either all profiles from ROM or none.

The reasons that could make my mouse use its ROM profiles are:
 - Invalid profile list: invalid addresses or all profiles disabled
 - Invalid CRC for the profile list, or any profile

I could write anything in a profile, as long as the CRC is good, the profile is accepted (even absurd report rates are obeyed making the pointer unusable and transferring a new profile very slow).

The driver checks that the first byte of the profile is non-null and that the CRC is valid. It does not log anything (not even a debug message). This code comes from commit 72d74da, that, from its description, should have addressed PlasmaPower's issue, but it apparently failed.

---------

Adding checks on the profile list should be easy and not controversial.

@bentiss, since you are the author of the current code, I'd like your opinion. I think the driver should try to mimic the mouse behavior and not default to ROM profile by profile individually. The first byte check looks useless to me (it failed for PlasmaPower's second profile) and could be remove. A CRC error should make the driver reread the whole profile list from ROM instead of just the current profile (that may not be an easy change). Is reading the profiles from the ROM enough to solve this? Will all the profiles be copied from ROM on the first change or just the changed profile (leaving invalid data for the other)?

Or we could just print errors and provides a way to easily write default profiles to the mouse in case something goes wrong. But how that would work with dbus clients like piper?

**Comment by whot** [comment] 2017-08-28 05:05
> Or we could just print errors and provides a way to easily write default profiles to the mouse in case something goes wrong. But how that would work with dbus clients like piper?

Things should only ever go wrong on `Commit()`. The long-term strategy is that the dbus api gives piper enough information to know what is acceptable and thus `commit` always succeeds. Anytime it fails, ratbagd should update the properties accordingly and that will be seen by piper (i.e. error code from commit, then a flurry of device state updates). So on the libratbag side we're quite flexible here, the only requirement is that ratbagd resyncs on error.

**Comment by bentiss** [comment] 2017-08-28 08:51
> @bentiss, since you are the author of the current code, I'd like your opinion. I think the driver should try to mimic the mouse behavior and not default to ROM profile by profile individually. The first byte check looks useless to me (it failed for PlasmaPower's second profile) and could be remove. A CRC error should make the driver reread the whole profile list from ROM instead of just the current profile (that may not be an easy change). Is reading the profiles from the ROM enough to solve this? Will all the profiles be copied from ROM on the first change or just the changed profile (leaving invalid data for the other)?

I'd say we should match the device behavior. If the mouse fallbacks on the ROM profile if a CRC fail, we should do the same. I'll look into what the Windows program does and will mimic the same behavior.

**Closed** 2017-09-13 07:21 UTC
