### ISSUE TITLE
Support for Logitech M510

### ISSUE THREAD

**Issue by IHATEEVERYTHING1** [libratbag/libratbag#1345] opened 2022-09-16 04:20 UTC
I've been working with making a device file for M510, but for some reason I can't get it to work with this mouse.
I would be very grateful if we could get this fixed in the future. I also have not found any suitible programs other than this, so please take this to hearing.
(Even if this doesn't get officially added, could someone help me with setting this up personally?)

**Comment by staticssleever668** [comment] 2022-10-11 07:58
Duplicate of #714.

**Closed by staticssleever668** 2022-10-11 07:58 UTC
Labels: enhancement
