### ISSUE TITLE
ratbag error: Unknown driver roccat-kone-pure in roccat-kone-pure.device

### ISSUE THREAD

**Issue by qherreros** [libratbag/libratbag#1347] opened 2022-09-20 09:06 UTC
Hello, thank you for your work. I think I have a strange Kone Pure version (SE version, not SEL see screenshots). I had to add a new usb id:

[Device]
Name=Roccat Kone Pure
DeviceMatch=usb:1e7d:2dc2;usb:1e7d:2dbe;usb:1e7d:2dcb`;usb:1e7d:2dca`
Driver=roccat-kone-pure

It is still broken though, the driver is not recognized.

**Information**

- `ratbagd` version (`ratbagd --version`): 0.16
- Distribution: Fedora 36
- Kernel version (ex. `uname -srmo`): Linux 5.19.9-200.fc36.x86_64 x86_64 GNU/Linux

Device info (if applicable):
```
$ ratbagctl <device> info
OUTPUT HERE
```

**Describe the bug**
My Roccat Kone Pure is not recognized
![image](https://user-images.githubusercontent.com/7406885/191216293-366aa6d1-7e3d-417d-a9de-9c3e46470c98.png)

**To Reproduce**
1. Start daemon
2. See error

**Logs**

![image](https://user-images.githubusercontent.com/7406885/191216853-64ffe676-f187-49ac-b933-dda18ea6af8b.png)

**Comment by staticssleever668** [comment] 2022-10-10 11:28
Hello, this has been fixed in not released yet libratbag v0.17. :)
Duplicate of #1006.
Fixed in #1011.

**Closed by staticssleever668** 2022-10-10 11:28 UTC
Labels: bug
