### ISSUE TITLE
Logitech G402 support

### ISSUE THREAD

**Issue by Macellatore** [libratbag/libratbag#471] opened 2018-03-28 13:19 UTC
I own both a g400 and a g402 mouse, and i see there's no official support for these models.
Is there anything i can do to help? My skills are limited but i'd be glad to contribute.
I see both models are present in the [device-notes page](https://libratbag.github.io/device-notes/) even though the info about them is not complete. Does it mean they are already WIP?

**Comment by phomes** [comment] 2018-03-28 13:46
I think that the G402 should be supported. It probably just needs a [device file](https://github.com/libratbag/libratbag/tree/master/data/devices) and a [svg file](https://github.com/libratbag/libratbag/tree/master/data/gnome).

The G400 is likely a close relative to the G400s, which I have one of. They do not use the HID++ protocol so will need to be reverse engineered.

A good start would be to plug the mice in and paste here the output of the command `lsusb`

**Comment by Macellatore** [comment] 2018-03-28 21:31
@FFY00: I tried creating a device file for the g402 but without a proper svg file (i'll work on it). Piper showed both the dpi and led configuration window, but no buttons window. The DPI one worked fine, but applying changes to the LED one has no effect.
I tried the same for the g400 but seems like Piper won't find the device.

@phomes: here's the output for both:
```
Bus 001 Device 003: ID 046d:c07e Logitech, Inc. G402 Gaming Mouse
Bus 001 Device 004: ID 046d:c245 Logitech, Inc. G400 Optical Mouse
```

**Comment by whot** [comment] 2018-04-02 23:15
you'll need to create a `.device` file first to assign a driver, then you should get the full debug spew, including whatever doesn't work on the device :)

**Comment by Macellatore** [comment] 2018-04-03 19:25
I'm not really sure how i did it, but here it is:
```
[tommy@tommy-arch builddir]$ sudo /home/tommy/Projects/mouse/libratbag/builddir/ratbagctl.devel list -vvv
ratbag debug: driver match found: Test driver
ratbag debug: Logitech Gaming Mouse G402 is device '/dev/hidraw0'.
ratbag debug: Logitech Gaming Mouse G402 is device '/dev/hidraw1'.
ratbag debug: report ID 01
ratbag debug: report ID 03
ratbag debug: report ID 04
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag raw: hidpp write: 11 01 00 18 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:  11 01 ff 00 18 0a 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag debug:     HID++ error from the device (1): Undocumented error code (0a)
test_device: Test device 
```

**Comment by whot** [comment] 2018-04-03 22:31
> ratbag debug: driver match found: Test driver

that indicates your `Driver=hidpp20` line assigns the test driver? or do you have the hidpp20 driver assigned?

**Comment by FFY00** [comment] 2018-04-04 20:06
Seems that `hidpp20` was partially successful. If you want full support, we need to reverse engineer the protocol. I am waiting for @phomes to send me some dumps for his `G400s`.

**Comment by phomes** [comment] 2018-04-05 21:25
I created a separate issue for the G400: #473

**Comment by Macellatore** [comment] 2018-04-06 11:32
Allright, so the setup to start gathering info on the protocol is a Windows vm + wireshark, right? I'll get it going.

**Comment by dslul** [comment] 2018-06-06 13:41
I have some dumps for the g402 at this page: https://github.com/dslul/logiconf/tree/master/other/dumps

I got leds configuration working in my program, I didn't have time to implement the rest, but iirc hid++2.0 should work for everything.

**Comment by dslul** [comment] 2018-06-06 20:54
I rebooted the system and now it works. I modified the g502 svg to get piper to work with this mouse, dpi settings seem to work good, leds not so well (10ff053d000000 must be send at the end to apply the configuration, as I wrote in my dumps). 
The buttons remap section does not appear. I don't know why.

![image](https://user-images.githubusercontent.com/6121202/41064605-55d7cc62-69dc-11e8-8b86-c6baf113705b.png)

![image](https://user-images.githubusercontent.com/6121202/41064620-5efbcb90-69dc-11e8-9150-27c7e3d7d9e7.png)


[logitech-g402.svg.zip](https://github.com/libratbag/libratbag/files/2078131/logitech-g402.svg.zip)

**Comment by dslul** [comment] 2018-06-08 14:36
Led settings do not work correctly, even though the mouse uses hidpp2 function 5 as in other mice (as the g502). See [this post](https://github.com/cvuchener/hidpp/issues/1#issuecomment-275946557) in my discussion with cvuchener for details on how led settings should work.

**Comment by xCuri0** [comment] 2018-12-26 11:00
@dslul where can i get your branch with the modifications for this mouse to work ?

**Comment by dslul** [comment] 2019-01-03 09:01
> @dslul where can i get your branch with the modifications for this mouse to work ?

@xCuri0 try this fork: https://github.com/dslul/libratbag
I can't test it at the moment, tell me if there is something wrong.
If you want to configure LEDs or fusion engine (because they are specific settings and won't work on libratbag) use logiconf: https://github.com/dslul/logiconf/releases

**Comment by bentiss** [comment] 2019-01-03 10:12
Regarding the LED settings, I can reproduce the issues you are having with my non RGB G502.

A simple patch would be to simply revert the HW control once configured but that would mean we can not configure LED 0 and 1.
OTOH, keeping the SW control means that we have to change the LEDs values of the DPIs/profiles ourself, which we are not doing, so probably better to keep the device in HW mode.

Also there is one thing that I realized: the 0x1300 feature is not per profile, so there is no point in attaching the various current values of the LEDs to a specific profile.

Last, @dslul could you open a PR with your SVG and G402 support? It seems in a good shape.

**Comment by dslul** [comment] 2019-01-03 14:46
I want to test it before doing a PR( I don't have the mouse right now). @xCuri0 can you test it and see if it works?
@bentiss does the button remap tab appear with your non rgb g502?

**Comment by bentiss** [comment] 2019-01-03 14:59
> @bentiss does the button remap tab appear with your non rgb g502?

looks like it does.
I do not think piper is able to properly configure the logo LED as it only provides settings for on/off when the LED supports breathing/off (and with breathing with duration of 0 being still)

**Comment by xCuri0** [comment] 2019-01-04 07:17
@dslul it seems like you haven't changed the code and only the device file so would be using the libratbag from the ubuntu ppa ?

**Comment by dslul** [comment] 2019-01-04 09:44
> @dslul it seems like you haven't changed the code and only the device file so would be using the libratbag from the ubuntu ppa ?

@xCuri0 you need to recompile from source because I also changed meson.build. Tell me if you have any problem.

**Comment by CharoSW** [comment] 2019-01-04 13:06
Quick question about functionality support: is it a device limitation that I can't see a way to configure the "g-shift" (which is called second-mode by libratbag) functions, or is it a general libratbag problem?

**Comment by bentiss** [comment] 2019-01-04 13:22
> Quick question about functionality support: is it a device limitation that I can't see a way to configure the "g-shift" (which is called second-mode by libratbag) functions, or is it a general libratbag problem? Happy to open a new issue if that's required.

I think this is something we never sorted out:
- you can assign a special key `second-mode` that triggers the G-shift
- you can not assign the buttons while in the G-Shift mode (at least not in ratbagctl)

IIRC, when working on the Roccat driver I duplicated every button, but that created a massive amount of visual data.

So there are 2 problems:
- one UI problem (how do we present these from the UI) -> that would be a piper issue
- one protocol problem: I am not sure how we can configure an alternate mapping for a button.

**Comment by CharoSW** [comment] 2019-01-04 13:32
> > Quick question about functionality support: is it a device limitation that I can't see a way to configure the "g-shift" (which is called second-mode by libratbag) functions, or is it a general libratbag problem? Happy to open a new issue if that's required.
> 
> I think this is something we never sorted out:
> 
>     * you can assign a special key `second-mode` that triggers the G-shift
> 
>     * you can not assign the buttons while in the G-Shift mode (at least not in ratbagctl)
> 
> 
> IIRC, when working on the Roccat driver I duplicated every button, but that created a massive amount of visual data.
> 
> So there are 2 problems:
> 
>     * one UI problem (how do we present these from the UI) -> that would be a piper issue
> 
>     * one protocol problem: I am not sure how we can configure an alternate mapping for a button.

Happy for me to open an issue for this support then?

**Comment by bentiss** [comment] 2019-01-04 13:38
> Happy for me to open an issue for this support then?

Sure why not?

However, some development would be even better :)

**Comment by xCuri0** [comment] 2019-01-08 05:15
@dslul built the latest libratbag with your patches and button control works. DPI level control also works properly now and doesn't crash

LED control still doesn't work

**Comment by dslul** [comment] 2019-01-08 15:13
@xCuri0 
> Would there be any way to add custom controls like the fusion engine ?

Since it's a device specific feature (and only for the G402 from what I know), I don't think it will ever be implemented or allowed in libratbag.

> LED control kinda works for the G logo. The color control shows even though it shouldn't and I can change the brightness and breathing duration. Setting it to off doesn't work so instead you have to put the brightness to minimum to turn it off.

Try my fork again, which now includes bentiss' patch.

**Comment by Hjdskes** [comment] 2019-01-09 13:49
Can this be closed with #602 merged?

**Comment by dslul** [comment] 2019-01-10 10:04
> @dslul Does libratbag have a way to add device specific functions ?

Actually, it should be pretty straightforward in this case. Just add support for feature 0x2400:
read status, function 0, {0,0,0}, returns 1 or 0
enable: function 1, {1,0,0}
disable: function 1, {1,0,0}).
Then add a tab in piper for those devices that support said feature.

**Comment by FFY00** [comment] 2019-08-14 09:19
The G402 is working.

**Closed by FFY00** 2019-08-14 09:19 UTC
Labels: device-specific
