### ISSUE TITLE
(help) Adding Roccat Kova AIMO support

### ISSUE THREAD

**Issue by anthonyclarka2** [libratbag/libratbag#1190] opened 2021-07-19 13:37 UTC
I have a couple of questions:

**Question:** The Roccat Kova mouse has 2 LEDs, on the wheel and on the base. Where do you name those locations?

**Question:** Is there a driver file like `driver-roccat.c` that has LEDs defined and is a good example for someone looking to modify an existing driver?

**Question:** What test information do you want included in a pull request?

I am creating a .device file for the Roccat Kova AIMO ambidextrous mouse.
Product page: https://www.roccat.com/products/kova-aimo

Using the device file below, my mouse is recognized but with the incorrect number of buttons and no LEDs. I understand that I need to create a new driver .c file to fully support it, and I'll create a PR once I'm happy with how it is working. If there are good examples for Piper, I will add the SVG to that project too.

```
[Device]
Name=Roccat Kova Aimo
DeviceMatch=usb:1e7d:2cee
Driver=roccat
[Driver/roccat]
Leds=2
```

**Comment by WalnussPower** [comment] 2021-07-27 22:45
This seems like a duplicate of or at least related to https://github.com/libratbag/libratbag/issues/929

**Closed** 2021-11-03 15:05 UTC
Labels: duplicate, device support

**Comment by perigoso** [comment] 2021-11-03 16:13
Feel free to reopen
