### ISSUE TITLE
[hidpp10] Profile switching and pages

### ISSUE THREAD

**Issue by cvuchener** [libratbag/libratbag#15] opened 2015-09-16 19:06 UTC
There are several points of which I am unsure about profiles. I think there is need for a discussion on this.

In the code, I have seen you use three profiles for the G500s. But I have only seen LGS use two: the temporary one in page 0 and a permanent one in the memory (page 2 for my G500 and I think my G500s use this one too). Actually you can write as many profiles as you can fit in memory, but they can only be switched from the driver, so it is not really useful.

The CMD_PROFILE command (0x0F), is one of the command I have documented that I least understand. It did not always behave like I intended in ways I did not manage to reproduce. I must be missing something.
But I know never found a way to get from where in the memory the current profile. I don't know how hidpp10_get_current_profile could be implemented.

About the page for the default permanent profile: I mainly tested the commands on my G500 and I quite sure it is on page 2, but I am less certain about the G500s, I will redo some tests. Or maybe there is something else that determine the location of the default profile.

**Comment by cvuchener** [comment] 2015-09-17 14:00
I have tested again, the default profile is definitely on page 2 on my G500s.

Some info on the device:
```
$ cat /sys/bus/usb/devices/1-3/{idVendor,idProduct,product,bcdDevice}
046d
c24e
G500s Laser Gaming Mouse
8401
```

**Comment by whot** [comment] 2015-09-17 14:22
I don't have access to the G500s at the moment, it's the only device I didn't bring with me to XDC :) so sorry, I can't test this atm but since I'll be offline for 3 weeks after this I'm happy to merge a fix that works on the G500 and then fix it after if it breaks the G500s.

As for the command: I don't have any better information, your document is the reference here.

**Comment by bentiss** [comment] 2015-09-24 17:37
My bad, wrong fix in the commit message

**Comment by bentiss** [comment] 2015-11-26 22:09
I think we can close this one now:
- the profile directory is now understood and implemented in libratbag
- you can basically write anything you want on the mouse, but if the crc is not valid, the mouse discards the page and use factory default. This is why changing settings without changing the crc gives some weird and unexpected results.

**Closed by bentiss** 2015-11-26 22:09 UTC

**Comment by cvuchener** [comment] 2015-11-26 22:58
> you can basically write anything you want on the mouse, but if the crc is not valid, the mouse discards the page and use factory default. This is why changing settings without changing the crc gives some weird and unexpected results.

Are you sure about that? I need to make some tests with page 1, but for profiles and macros I have been using invalid crc without problems.

**Comment by bentiss** [comment] 2015-11-27 05:58
> Are you sure about that?

I am sure that the HID++ 2.0 devices reject pages when the crc is wrong.
And I inferred this given that there was a discussion regarding the profile directory which was not taken into account when written on it without the crc.
Maybe they enforced the crc only for page 0x01, or maybe I am completely wrong :)

**Comment by cvuchener** [comment] 2015-11-27 09:52
You are right. Writing the crc, allow me to change the profile directory on my G500. Nice find, I did not think about trying that since it worked for other pages without it.

By the way, I think I found out what operation 4 with register 0xA0 is used for: it can computes the crc of pages (use the page number as source offset).

**Comment by cvuchener** [comment] 2015-11-27 10:16
You can add two special keys: 0x0010 profile up, 0x0020 profile down. The G500 does not seem to handle special keys with more than one bit: 0x0009 (cycle resolution) behave like 0x0008 (resolution down) and 0x0011 (cycle profile) like 0x0010 (profile up).

**Comment by bentiss** [comment] 2015-11-27 21:36
> I did not think about trying that since it worked for other pages without it.

Hmm, that means we have mice around with an invalid crc. I should probably allow them and not discard the page as I am currently doing.

> I think I found out what operation 4 with register 0xA0

You made a good guess. We have the spec for register 0xA0 and you are right. I am not sure we actually need to ask the device for the crc while we can just compute it in the host.

Regarding A0, it is used to do generic memory management and seems the only way to write in flash. The problem is that to be able to write to the device, we do not have all of the documentation in the HID++ spec. I have looked at what LGS does, and it seems awfully complex compared to the HID++ 2.0 devices.

> You can add two special keys: 0x0010 profile up, 0x0020 profile down.

done locally

> The G500 does not seem to handle special keys with more than one bit: 0x0009 (cycle resolution) behave like 0x0008 (resolution down) and 0x0011 (cycle profile) like 0x0010 (profile up).

sigh. They might just used the same bit mask than the buttons and then realized it made no sense and started adding values in the holes...

**Comment by cvuchener** [comment] 2015-11-28 09:46
> Regarding A0, it is used to do generic memory management and seems the only way to write in flash. The problem is that to be able to write to the device, we do not have all of the documentation in the HID++ spec. I have looked at what LGS does, and it seems awfully complex compared to the HID++ 2.0 devices.

You can write in flash using the 0x9x subIDs. LGS uses a overly complicated method. You can simply fill the page with 0xFF using 0xA0 operation 2, then send your data in one 512 byte block (or smaller if you prefer) directly to its destination. The only real constraint is that you cannot overwrite some data without overwriting the whole page.
