### ISSUE TITLE
Logitech G Pro Superlight possibly missing PID

### ISSUE THREAD

**Issue by RicArch97** [libratbag/libratbag#1324] opened 2022-07-03 04:01 UTC
**Information**

- `ratbagd` version: 0.15
- Distribution: Void Linux
- Kernel version: Linux 5.18.9_1 x86_64 GNU/Linux

**Describe the bug**
Possible PID missing for the G Pro superlight. Mine has `046d:c547` which is not listed in the device data,  so it isn't detected.
```
Bus 003 Device 004: ID 046d:c547 Logitech, Inc. USB Receiver
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0        64
  idVendor           0x046d Logitech, Inc.
  idProduct          0xc547
  bcdDevice            4.02
  iManufacturer           1 Logitech
  iProduct                2 USB Receiver
  iSerial                 0
```
**Logs**
```
Initializing libratbag
ratbag debug: New device: ITE Tech. Inc. ITE Device(8595)
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 048d:8297
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c547
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c547
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c547
ratbag debug: New device: Razer Razer Huntsman Tournament Edition
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1532:0243
ratbag debug: New device: Razer Razer Huntsman Tournament Edition
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1532:0243
ratbag debug: New device: Razer Razer Huntsman Tournament Edition
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1532:0243
ratbag debug: New device: Razer Razer Huntsman Tournament Edition
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1532:0243
ratbag debug: New device: Cooler Master Technology Inc. ARES
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 2516:014d
ratbag debug: New device: Cooler Master Technology Inc. ARES
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 2516:014d
ratbag debug: New device: Cooler Master Technology Inc. ARES
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 2516:014d
DBus server ready
```

**Additional context**
Not sure if I have a newer version of the product?

**Comment by staticssleever668** [comment] 2022-10-09 19:42
Hi, `c547` is the receiver ID. As far as I know Linux is supposed to expose the device behind it with mouse's proper PID (the one you get when the mouse is connected by wire). 
Can you check if it works while connected by wire?

**Comment by K0bin** [comment] 2022-10-09 20:38
It does.

**Comment by staticssleever668** [comment] 2022-10-09 21:44
@K0bin, thanks for your feedback, but I would also like to hear confirmation from @RicArch97. By the way, since you've left a comment, does it too not work in wireless mode for you? 

In case it *does* work by wire but not in wireless mode, it's a kernel bug IIUC.

**Comment by K0bin** [comment] 2022-10-09 21:47
It does indeed work when connected with the wire but doesn't work wirelessly.

**Comment by staticssleever668** [comment] 2022-10-09 23:00
@K0bin, thanks for clarifying.
Duplicate of #1119.

**Closed by staticssleever668** 2022-10-09 23:00 UTC
Labels: bug
