### ISSUE TITLE
Mouse detected by ratbagd but does not show up in ratbagctl (SteelSeries Rival 310)

### ISSUE THREAD

**Issue by preppie22** [libratbag/libratbag#1588] opened 2024-02-16 07:32 UTC
**Information**

- `ratbagd` version (`ratbagd --version`): 0.17
- Distribution: Fedora 39 KDE
- Kernel version (ex. `uname -srmo`): `Linux 6.7.4-200.fc39.x86_64 x86_64 GNU/Linux`

Device info (if applicable): SteelSeries Rival 310
Can't generate ratbagctl info because device isn't detected.

**Describe the bug**
I have a SteelSeries Rival 310 which is working correctly and showing up in settings as well as in `lsusb`. When I run `sudo ratbagd --verbose=raw` the mouse seems to be detected correctly, but when the daemon is running, it does not show up with `ratbagctl` and it returns `No devices available.`

**To Reproduce**
1. Connect SteelSeries Rival 310 mouse to PC.
2. Run `sudo ratbagd --verbose=raw` and note that mouse appears and driver is loaded.
3. Start the ratbagd service with `sudo systemctl start ratbagd.service`
4. Run `ratbagctl` and note that `No devices available is displayed.`

**Logs**
Please start the daemon with verbosity and reproduce the issue.

First make sure it isn't running already.
```
$ ratbagd --verbose=raw
Initializing libratbag
ratbag debug: New device: DCMT Technology USB Lavalier Microphone
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 31b2:0011
ratbag debug: New device: Creative Technology Ltd Sound Blaster X4
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 041e:3278
ratbag debug: New device: SteelSeries SteelSeries Rival 310 eSports Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw3'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw4'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: New device: SteelSeries SteelSeries Rival 310 eSports Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw3'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw4'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: New device: SteelSeries SteelSeries Rival 310 eSports Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw3'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw4'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: New device: Keychron Keychron C1
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 05ac:024f
ratbag debug: New device: Keychron Keychron C1
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 05ac:024f
DBus server ready

```

**Additional context**
This is the status of ratbagd service and what I get when ratbagctl is run
```
$ systemctl status ratbagd.service 
● ratbagd.service - Daemon to introspect and modify configurable mice
     Loaded: loaded (/usr/lib/systemd/system/ratbagd.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Thu 2024-02-15 23:25:53 PST; 7s ago
   Main PID: 9566 (ratbagd)
      Tasks: 1 (limit: 18996)
     Memory: 636.0K
        CPU: 23ms
     CGroup: /system.slice/ratbagd.service
             └─9566 /usr/bin/ratbagd

Feb 15 23:25:53 home-fedora systemd[1]: Starting ratbagd.service - Daemon to introspect and modify configurable mice...
Feb 15 23:25:53 home-fedora systemd[1]: Started ratbagd.service - Daemon to introspect and modify configurable mice.
$ ratbagctl
No devices available.
```
I have tried changing the USB port where the mouse is connected but have the same issue. Since ratbagctl doesn't detect the mouse, it's not detected by Piper either. However, I'm able to see it in the KDE settings. Also attaching output of `lsusb` if it helps.
```
$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 31b2:0011 DCMT Technology USB Lavalier Microphone
Bus 001 Device 003: ID 041e:3278 Creative Technology, Ltd Sound Blaster X4
Bus 001 Device 004: ID 05a3:9331 ARC International Camera
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 2109:2815 VIA Labs, Inc. USB2.0 Hub             
Bus 003 Device 004: ID 05ac:024f Apple, Inc. Aluminium Keyboard (ANSI)
Bus 003 Device 005: ID 1038:1720 SteelSeries ApS Mouse
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 004 Device 002: ID 2109:0815 VIA Labs, Inc. USB3.0 Hub
```

**Comment by staticssleever668** [comment] 2024-02-17 10:15
Hi! In short, this is a duplicate of #1438. Until a new libratbag release I suggest you compiling from source or trying out rivalcfg.

**Closed by staticssleever668** 2024-02-17 10:15 UTC
Labels: bug

**Comment by preppie22** [comment] 2024-02-17 15:08
Thank you for your time! I did try to compile from source but I couldn't get ratbagd to start. It gave me a permission denied error despite using sudo. The systemd service was not found either.

**Comment by staticssleever668** [comment] 2024-02-17 15:20
Pay attention to install prefix, I'd guess that's the issue for you:
https://github.com/libratbag/libratbag/wiki/Building-from-source#overwriting-the-system-installation

Also note, for master branch of librabag you would also need master branch of Piper.
https://github.com/libratbag/piper/wiki/Installation#building-from-source
Build dependencies for Ubuntu for reference, if you run into trouble with them:https://github.com/libratbag/piper/blob/d553d97b3e5517441771044bf24e1c4eddfa74f6/.github/workflows/main.yml#L6-L10

**Comment by preppie22** [comment] 2024-02-17 15:38
I did follow the steps from the guide you told me and had used the `/usr` prefix, but that didn't seem to fix the issue. This is what I'm seeing:
```
$ sudo ratbagd
[sudo] password for ######: 
ratbagd error: Failed to start ratbagd: Permission denied
$ ratbagctl
Unable to connect to ratbagd: No one currently owns org.freedesktop.ratbag1
```
This appears to be similar to issue #781 but that seems to be closed because the author did not wish to pursue it further.

**Comment by preppie22** [comment] 2024-02-17 15:49
> I did follow the steps from the guide you told me and had used the `/usr` prefix, but that didn't seem to fix the issue. This is what I'm seeing:
> 
> ```
> $ sudo ratbagd --verbose=raw
> [sudo] password for ######: 
> Starting ratbagd version 0.17 (API version 2)
> Initializing libratbag
> ratbagd error: Failed to start ratbagd: Permission denied
> $ ratbagctl
> Unable to connect to ratbagd: No one currently owns org.freedesktop.ratbag1
> ```
> 
> This appears to be similar to issue #781 but that seems to be closed because the author did not wish to pursue it further.
> 
> Here are the contents of `/usr/share/dbus-1/system.d/org.freedesktop.ratbag1.conf`:
> 
> ```
> <?xml version="1.0"?> 
> <!DOCTYPE busconfig PUBLIC
>         "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
>         "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
> 
> <busconfig>
> 
>         <policy user="root">
>                 <allow own="org.freedesktop.ratbag1"/>
>                 <allow send_destination="org.freedesktop.ratbag1"/>
>                 <allow receive_sender="org.freedesktop.ratbag1"/>
>         </policy>
> 
>         <policy context="default">
>                 <allow send_destination="org.freedesktop.ratbag1"/>
>                 <allow receive_sender="org.freedesktop.ratbag1"/>
>         </policy>
> 
> </busconfig>
> ```
> 
> Edit: Added more context.

Ok, I fixed this! Reloaded the dbus service and it started working. Leaving this here for anyone else that comes across this issue:
```
sudo systemctl reload dbus.service
```

Thank you for your time and help!
