### ISSUE TITLE
Failed to get HID++1.0 device for Logitech M570

### ISSUE THREAD

**Issue by JustchillinIDK** [libratbag/libratbag#1281] opened 2022-02-09 20:07 UTC
**Information:**

- Distribution: Linux Mint 20.3
- Kernel info (``uname -srmo``): ``Linux 5.11.0-34-generic x86_64 GNU/Linux``
- Device: Logitech M570 wireless trackball
- ratbagd version: 0.13

**Description:**
I installed using ``sudo apt install ratbagd``.
When I attempt to run it outputs:
```
ratbag error: Failed to get HID++1.0 device for Logitech M570
ratbag error: libratbag bug: Logitech M570: invalid number of profiles (0)
fish: “sudo ratbagd” terminated by signal SIGSEGV (Address boundary error)
```
In verbose mode:
```
Initializing libratbag
ratbag debug: New device: Logitech M570
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp10
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0x1028
ratbag debug: Logitech M570 is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: - HID report ID 20
ratbag debug: - HID report ID 21
ratbag raw: Fetching individual features (0x1)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 01 | 00 00 00
ratbag raw: hidpp write:  10 00 81 01 00 00 00
ratbag raw: hidpp read:   10 01 81 01 02 00 00
ratbag raw: hidpp10 rx:  10 | 00 | 81 | 01 | 02 00 00
ratbag raw: Fetching HID++ notifications (00)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 00 | 00 00 00
ratbag raw: hidpp write:  10 00 81 00 00 00 00
ratbag raw: hidpp read:   10 01 81 00 10 00 00
ratbag raw: hidpp10 rx:  10 | 00 | 81 | 00 | 10 00 00
ratbag raw: Fetching current resolution (0x63)
ratbag raw: hidpp10 tx:  10 | 00 | 83 | 63 | 00 00 00
ratbag raw: hidpp write:  10 00 83 63 00 00 00
ratbag raw: hidpp read:   10 01 8f 83 63 01 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_SUBID (01)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 83 | 63 01 00
ratbag raw: Fetching LED status (0x51)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 51 | 00 00 00
ratbag raw: hidpp write:  10 00 81 51 00 00 00
ratbag raw: hidpp read:   10 01 8f 81 51 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 51 02 00
ratbag raw: Fetching USB refresh rate (0x64)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 64 | 00 00 00
ratbag raw: hidpp write:  10 00 81 64 00 00 00
ratbag raw: hidpp read:   10 01 8f 81 64 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 64 02 00
ratbag raw: Fetching optical sensor settings (0x61)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 61 | 00 00 00
ratbag raw: hidpp write:  10 00 81 61 00 00 00
ratbag raw: hidpp read:   10 01 8f 81 61 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 61 02 00
ratbag raw: Fetching current profile (0xf)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 0f | 00 00 00
ratbag raw: hidpp write:  10 00 81 0f 00 00 00
ratbag raw: hidpp read:   10 01 8f 81 0f 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 0f 02 00
ratbag error: Failed to get HID++1.0 device for Logitech M570
ratbag error: libratbag bug: Logitech M570: invalid number of profiles (0)
fish: “sudo ratbagd --verbose” terminated by signal SIGSEGV (Address boundary error)
```
**To reproduce:**
_Connect a M570 trackball and run the program_
**In short:**
device not detected program doesn't start

**Comment by pdl-7261** [comment] 2022-02-10 04:29
I am having the exact same issue:

`~$ sudo ratbagd --verbose
Initializing libratbag
ratbag debug: New device: Logitech M570
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp10
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0x1028
ratbag debug: Logitech M570 is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: - HID report ID 20
ratbag debug: - HID report ID 21
ratbag raw: Fetching individual features (0x1)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 01 | 00 00 00
ratbag raw: hidpp write:  10 00 81 01 00 00 00
ratbag raw: hidpp read:   10 01 81 01 02 00 00
ratbag raw: hidpp10 rx:  10 | 00 | 81 | 01 | 02 00 00
ratbag raw: Fetching HID++ notifications (00)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 00 | 00 00 00
ratbag raw: hidpp write:  10 00 81 00 00 00 00
ratbag raw: hidpp read:   10 01 81 00 10 00 00
ratbag raw: hidpp10 rx:  10 | 00 | 81 | 00 | 10 00 00
ratbag raw: Fetching current resolution (0x63)
ratbag raw: hidpp10 tx:  10 | 00 | 83 | 63 | 00 00 00
ratbag raw: hidpp write:  10 00 83 63 00 00 00
ratbag raw: hidpp read:   10 01 8f 83 63 01 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_SUBID (01)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 83 | 63 01 00
ratbag raw: Fetching LED status (0x51)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 51 | 00 00 00
ratbag raw: hidpp write:  10 00 81 51 00 00 00
ratbag raw: hidpp read:   02 00 00 00 10 00 00 00
ratbag raw: hidpp read:   10 01 8f 81 51 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 51 02 00
ratbag raw: Fetching USB refresh rate (0x64)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 64 | 00 00 00
ratbag raw: hidpp write:  10 00 81 64 00 00 00
ratbag raw: hidpp read:   10 01 8f 81 64 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 64 02 00
ratbag raw: Fetching optical sensor settings (0x61)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 61 | 00 00 00
ratbag raw: hidpp write:  10 00 81 61 00 00 00
ratbag raw: hidpp read:   10 01 8f 81 61 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 61 02 00
ratbag raw: Fetching current profile (0xf)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 0f | 00 00 00
ratbag raw: hidpp write:  10 00 81 0f 00 00 00
ratbag raw: hidpp read:   10 01 8f 81 0f 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 0f 02 00
ratbag error: Failed to get HID++1.0 device for Logitech M570
ratbag error: libratbag bug: Logitech M570: invalid number of profiles (0)
Segmentation fault
`

**Comment by staticssleever668** [comment] 2022-10-10 12:36
Duplicate of #889.

**Closed by staticssleever668** 2022-10-10 12:36 UTC
