### ISSUE TITLE
Glorious Model I Wired Support

### ISSUE THREAD

**Issue by xanzoh** [libratbag/libratbag#1552] opened 2023-11-14 21:11 UTC
I've been searching for hours for a solution to have my mouse buttons identified. To my surprise still no support.
I play games disabled (missing left lower arm) and am in need to use additional mouse buttons to play games.
I just switched over to Linux and am having to dual-boot Windows for the time being, if this problem can be solved I would be overjoyed. Thank you for the current support!

**Comment by staticssleever668** [comment] 2023-11-16 18:27
Hi! This looks like a duplicate of #1327, if "Wired" is the same thing as usual "Glorious Model I".
What is the output of `lsusb` for you, @xanzoh?

**Comment by xanzoh** [comment] 2023-11-18 23:21
Hey thanks for the response i was reading the linked issue you sent, I have the "Wired" version of the Model I, and i can confirm it's the same issue (same lsusb output too.) As of now I've unfortunately returned back to Windows.

**Comment by staticssleever668** [comment] 2023-11-19 10:00
Yeah, as that issue says, Model I uses different protocol from older Model {O,D} and new Model {O,D} Wireless mice.
libratbag doesn't support it, and neither do I know any other utilities that do.
Sorry for not being of any help.

Closing as duplicate of #1327.

**Closed by staticssleever668** 2023-11-19 10:00 UTC
Labels: enhancement
