### ISSUE TITLE
G700s: Cannot set or use macros

### ISSUE THREAD

**Issue by calvertdw** [libratbag/libratbag#900] opened 2020-01-07 18:22 UTC
**Information**
- `ratbagd` version (`ratbagd --version`): 0.12
- Distribution: Arch Linux
- Kernel version: `Linux 5.4.8-arch1-1 x86_64 GNU/Linux`

**Describe the bug**
Macros show up as UNKNOWN and setting them with ratbagctl does not work. `info` will show that the macro has been mapped but the button still does not perform the macro.

**To Reproduce**
1. Plug in g700s (with macros already set from Windows)
2. Use Piper to try to set some macros. See the error "something went wrong"
3. Try to set the macro with `ratbagctl warbling-mara button 5 action set macro KEY_T`
4. Button does not perform macro

**Logs**
[output of sudo ratbagd --verbose=raw](https://github.com/libratbag/libratbag/files/4031842/log.txt)

```
$ ratbagctl warbling-mara info
warbling-mara - Logitech G700s Rechargeable Gaming Mouse
             Model: usb:046d:c07c:0
 Number of Buttons: 13
    Number of Leds: 0
Number of Profiles: 5
Profile 0: (active)
  Name: Work Default
  Report Rate: 1000Hz
  Resolutions:
    0: 2100x2100dpi (active)
    1: <disabled>
    2: <disabled>
    3: <disabled>
    4: <disabled>
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to macro '↕T'
  Button: 6 is mapped to UNKNOWN
  Button: 7 is mapped to 'button 5'
  Button: 8 is mapped to 'button 4'
  Button: 9 is mapped to macro '↕X'
  Button: 10 is mapped to UNKNOWN
  Button: 11 is mapped to 'button 4'
  Button: 12 is mapped to 'button 5'
Profile 1: (disabled)
Profile 2: (disabled)
Profile 3: (disabled)
Profile 4: (disabled)
```

**Comment by stephanlachnit** [comment] 2020-01-07 19:55
Thanks for the logs, maybe @FFY00 can help out, don't know the protocol and hence not even where the committing starts, if it even tries to do so or fails before.

**Comment by FFY00** [comment] 2020-01-07 21:15
Probably committing failed because the driver didn't know how to write that macro.

**Comment by calvertdw** [comment] 2020-01-08 16:57
Shouldn't the button action set command print an error if it fails? How does Piper get the error it displays? I can't find any errors in the logs even from `ratbagd` with verbose enabled.

**Comment by stephanlachnit** [comment] 2020-01-08 17:56
> Shouldn't the button action set command print an error if it fails? How does Piper get the error it displays? I can't find any errors in the logs even from `ratbagd` with verbose enabled.

All communication is done via dbus. I don't know if there is any way to get monitor dbus calls, but neither ratbag nor Piper provide a debug output on what they are doing and why it is failing in most cases.

**Comment by calvertdw** [comment] 2020-01-08 18:05
I went to a Windows computer and set the macros to the on-board profile(s) and confirmed them working on Windows. I moved the mouse back over to Linux and the macros do not work. I also:

1. Disabled ratbagd and rebooted
2. Ensured two different on-board profiles to be working on another Windows machine (plugged in USB)
3. Bring the mouse back over to the wireless receiver on Linux box
4. After logging into Linux desktop, the mouse macros do not do anything

This leads me to believe the problem is not writing the macros to the device (at least for setting via `ratbagctl`, but instead that the macros are not received by the OS somehow after I upgraded my kernel.

This worked before I upgraded my kernel yesterday. I wasn't able to set macros with Piper and still can't but I now think there are two separate issues that first seemed related but might not actually be:

1. Piper is unable to program macros to the device
2. The device is unable to send it's on-board programmed macros to the OS

**Comment by FFY00** [comment] 2020-01-08 18:28
> All communication is done via dbus. I don't know if there is any way to get monitor dbus calls

You can use `dbus-monitor`.
```
sudo dbus-monitor --system sender=org.freedesktop.ratbag1
```

> but neither ratbag nor Piper provide a debug output on what they are doing and why it is failing in most cases.

master should now spit out an error when failing to commit.

> I went to a Windows computer and set the macros to the on-board profile(s) and confirmed them working on Windows. I moved the mouse back over to Linux and the macros do not work. I also:
> 
>     1. Disabled ratbagd and rebooted
> 
>     2. Ensured two different on-board profiles to be working on another Windows machine (plugged in USB)
> 
>     3. Bring the mouse back over to the wireless receiver on Linux box
> 
>     4. After logging into Linux desktop, the mouse macros do not do anything
> 
> 
> This leads me to believe the problem is not writing the macros to the device (at least for setting via `ratbagctl`, but instead that the macros are not received by the OS somehow after I upgraded my kernel.
> 
> This worked before I upgraded my kernel yesterday. I wasn't able to set macros with Piper and still can't but I now think there are two separate issues that first seemed related but might not actually be:
> 
>     1. Piper is unable to program macros to the device
> 
>     2. The device is unable to send it's on-board programmed macros to the OS

Can you try Linux 5.5? So that it includes https://github.com/torvalds/linux/commit/992ff2cc9ec6e30ccc64c341b052e8ccb370db90.

**Comment by calvertdw** [comment] 2020-01-09 05:04
Still haven't tried 5.5. Just wanted to note that I have the same setup at home and it is working on `Linux 5.3.13-arch1-1 x86_64 GNU/Linux`

**Comment by calvertdw** [comment] 2020-01-13 16:46
I'm not sure how safe it is to upgrade to mainline. I might wait to try this until 5.5 is stable.

https://aur.archlinux.org/packages/linux-mainline/

**Comment by calvertdw** [comment] 2020-01-27 15:24
Looks like 5.5 is being released to stable. (https://www.kernel.org/)

**Comment by calvertdw** [comment] 2020-02-07 05:11
I have upgraded my kernel to 5.5.2 and I observe the same behavior.

**Comment by FFY00** [comment] 2020-02-07 15:46
Please set the macros in the original driver and see if they work with that kernel.

**Comment by Evils-Devils** [comment] 2020-03-16 01:10
i'm getting this issue on NixOS with linux 5.6.0-rc3 and libratbag 0.13

**Comment by Pshemas** [comment] 2020-03-28 13:43
I'm experiencing the same issue (and have been for years - can't recall when g700s actually worked with ratbag). When I monitor dbus events when using piper I see:

```
method return time=1585402868.362925 sender=:1.330 -> destination=:1.348 serial=306 reply_serial=488
method return time=1585402869.664366 sender=:1.330 -> destination=:1.348 serial=307 reply_serial=489
   uint32 0
error time=1585402869.664569 sender=:1.330 -> destination=:1.348 error_name=org.freedesktop.DBus.Error.UnknownMethod reply_serial=489
   string "Unknown method Commit or interface org.freedesktop.ratbag1.Device."
signal time=1585402869.665023 sender=:1.330 -> destination=(null destination) serial=309 path=/org/freedesktop/ratbag1/device/hidraw9; interface=org.freedesktop.ratbag1.Device; member=Resync
```

**Comment by FFY00** [comment] 2020-03-28 17:24
@Pshemas can you include the steps to reproduce?

**Comment by Pshemas** [comment] 2020-03-28 19:08
connect a g700s mouse and try to assign any macro.
It is completely broken :( - I can assign mouse buttons to those extra buttons, but not keyboard buttons.
It is even weirder - with those newer kernels settings I do in Logitech app on Windows are no longer recognized and do not work on Linux. When I connect the mouse to Windows box the macros I've set work, on Linux workstation don't. If you'd like to try it in some remote session etc I'll be happy to do it. I'm slowly loosing hope for those Logitech devices - the situation is not improving, actually it got worse (and it is not poke at you - rather at Logitech). I've been just chatting with a user that has G602 and he is reporting identical problems.

**Comment by Pshemas** [comment] 2020-03-28 19:24
[ratbag_issue_video.zip](https://github.com/libratbag/libratbag/files/4397747/ratbag_issue_video.zip)
this video should show howto reproduce it

**Comment by FFY00** [comment] 2020-03-28 20:02
That happens because the windows driver does it in software, we do it in hardware.

**Comment by Pshemas** [comment] 2020-03-28 20:29
ok, but the weird part to me. is that in the past I've been able to set up keys on Windows, then connect the mice to my Linux workstation and the keymap transferred over. It worked.
Now it is messed up - no workaround. Is there anything I could do to help in sorting this one out? Today I've started looking for alternative wireless mice, but the situation with wireless "gaming" mice and extra keys on Linux is a bit dire.

**Comment by Pshemas** [comment] 2020-03-28 23:15
addes verbose=raw to check what will be displayed there. I see:

`ratbagd error: error committing device (-1000)`

when trying to commit a macro key.

**Comment by Pshemas** [comment] 2020-03-29 11:19
for the moment I'm looking at assigning mice button presses to those extra keys and using additional apps that would map those to macros (xbindkeys, xvkvd etc). Quite a pita - one of the reasons I'm cheering up for projects like Ratbag / Piper.
While I've been discussing options on the net several other users reported problems (the most common was G602).

**Comment by CyanBlob** [comment] 2020-03-31 21:07
@FFY00 Are there any plans to add software support for this? Or is that outside the scope of the project?

**Comment by FFY00** [comment] 2020-03-31 21:10
It could be done but I don't think anyone is planning to. It uses the old protocol version which is only used on a relatively small number of devices.

Setting macros on new devices is not implemented yet but planned.

**Comment by CyanBlob** [comment] 2020-03-31 21:12
I see. How would I determine if my mouse uses the new or old protocol? It's the MX Vertical. This is my first time using ratbag, so sorry if this is a simple question lol

**Comment by FFY00** [comment] 2020-03-31 21:16
Ah, the MX Vertical uses the new one, but unfortunately doesn't support hardware macros. Only devices from the gaming line support macros. Most? devices productivity line will allow you to remap buttons though, just not to have macros.

The G700s was released in 2013, the devices released in the past few years 4~5? use the new protocol.

**Comment by calvertdw** [comment] 2020-03-31 22:49
@CyanBlob Let's keep this issue about hardware support for the g700s. It worked for me on Linux 5.4 as you can see above. Getting it back should be possible.

**Comment by hoshsadiq** [comment] 2020-04-01 13:56
Running 5.5.2 and I have the same issue. Logs give this: 

```
Apr 01 14:49:53 hosh-XPS-15-9560 ratbagd[31092]: ratbagd error: error committing device (-1000)
```

**Comment by FFY00** [comment] 2020-04-01 14:51
Can you run the daemon with verbosity and paste the output?

Kill the daemon if one is already running and:
```
sudo ratbagd --verbose=raw
```

**Comment by hoshsadiq** [comment] 2020-04-01 14:57
Here is the log: https://gist.github.com/hoshsadiq/1b882b4db9a7cc63d44e0e5fd9ca1a67

**Comment by FFY00** [comment] 2020-04-01 15:05
Could you try again with #943? That way we can see exactly what went wrong.

**Comment by hoshsadiq** [comment] 2020-04-10 17:33
@FFY00 sorry for the late reply, I came down with the virus and am still recovering.. I noticed your PR was already merged so I ran the latest master and here is the logs: https://gist.github.com/hoshsadiq/379764d3cf7016f44dc25c1bbb844e86

**Comment by FFY00** [comment] 2020-04-10 17:40
Looks like macros are not supported by the HID++ 1.0 driver.

https://github.com/libratbag/libratbag/blob/dba202ae8bd5fc1d0014e90bd0b89393c2a3f436/src/driver-hidpp10.c#L332

Are they supported in the Windows driver?

I don't see any reference to macro in the public documentation. If this works in Windows, their driver might be doing this in software instead of configuring the hardware.

**Comment by cvuchener** [comment] 2020-04-10 18:42
I have some HID++ 1.0 macro documentation here: https://github.com/cvuchener/g500/blob/master/doc/macro.md

It is mostly from G500/G500s reverse engineering but I think it is the same for the G700s.

**Comment by hoshsadiq** [comment] 2020-04-11 14:13
> Are they supported in the Windows driver?

It's been a long time since I used the g700s on Windows, however, I do recollect being able to assign `<Ctrl><Alt><Windows><left>` to buttons on my mouse. Whether or not they're macros or implemented in a different way, I'm not sure.

**Comment by calvertdw** [comment] 2020-04-12 23:08
@FFY00 Are you saying that since Linux 5.5, a different driver is used for g700s? Is there a way to reverse the change?

**Comment by FFY00** [comment] 2020-04-12 23:25
We had some changes in the driver. If you want to revert it you will need to use an older version of the driver and an older version of libratbag.

**Comment by FFY00** [comment] 2020-04-13 00:13
Could you try #950?

**Comment by hoshsadiq** [comment] 2020-04-14 07:13
Is it not possible to compile it and run it without installing?

```
$ sudo ./ratbagd --verbose=raw
Initializing libratbag
ratbagd error: Failed to start ratbagd: Invalid argument
$ sudo mv `which ratbagd`{,.bck}
$ sudo mv ./ratbagd /usr/bin/ratbagd
$ sudo ratbagd --verbose=raw
Initializing libratbag
ratbagd error: Failed to start ratbagd: Invalid argument
```

Anyway, after recompiling again, and installing it fully on the system this time, your branch allowed me to set the macro keys, but the buttons don't do anything once it's been applied. [logs](https://gist.github.com/hoshsadiq/bf5c7093428afef0bf2ab132e513829d)

**Comment by FFY00** [comment] 2020-04-14 11:19
There is:
```
$ mkdir build
$ cd build
$ meson .. --prefix=/usr
$ ninja
$ sudo ./ratbagd --verbose=raw
```

This seems weird, it worked on my G500. Only simple macros are supported though, like keypresses. Which macros did you configure?

**Comment by hoshsadiq** [comment] 2020-04-14 15:50
I configured the following:
![image](https://user-images.githubusercontent.com/600045/79245103-8f5e1a00-7e6f-11ea-987f-bc3dc5cdebc0.png)

I also just changed it to do a simpler keypress, namely just `D`, but still nothing.

Though unlikely, is there way I can validate that the mouse button is actually working? As the mouse is relatively old.

**Comment by FFY00** [comment] 2020-04-14 16:15
Yeah, that is not supported yet. We need to write the whole ratbagd <-> HID++ 2.0 macros translation, and implement some dynamic memory allocation for the mouse to store the macros.

A simple `D` should work. Does it look like this?

![piper-simple-macro](https://user-images.githubusercontent.com/11718923/79248303-92f3a000-7e73-11ea-96a9-6670283831ac.png)

**Comment by hoshsadiq** [comment] 2020-04-15 12:40
Yup:

![image](https://user-images.githubusercontent.com/600045/79338131-a14ac600-7f1e-11ea-96e1-1796800a064e.png)

**Comment by FFY00** [comment] 2020-04-15 12:47
You are editing profile 3, are you sure that is the active profile? You can't configure any complex macros or writting the settings to the device will fail, so please remove it.

**Comment by hoshsadiq** [comment] 2020-04-17 16:16
Definitely using the correct profile. I ended up installing the official software from Logitech on my wife's mbp.. First I noticed that it seems the `D` macro was actually written correctly. On her mbp it wrote `D` correctly when the button was pressed.

Then also, it seems the macros get written differently (or at least, it's shows different on the UI). Notice below screenshot. Button `G7` was set to `Ctrl+Super+Alt+Right` using the official Logitech software, and `G6` was set to `Ctrl+Super+Alt+Left` using piper. Notice `G7` shows `Multikey Macro`, yet `G6` shows the actual keys. Would this be a reason why it doesn't work?

![image](https://user-images.githubusercontent.com/600045/79590170-87e87c00-80ce-11ea-9b3d-3a751c7699bd.png)

Coming back to piper, it shows as below. `Macro: none` is `G7` and `Unknown` is `G6`.

![image](https://user-images.githubusercontent.com/600045/79590519-0e04c280-80cf-11ea-8cf1-311b0fea77b7.png)

**Comment by FFY00** [comment] 2020-04-17 16:23
Maybe the buttons are switched in piper, does it show correctly in `ratbagctl`?

```
ratbagctl your-device info
```

**Closed** 2020-04-18 01:31 UTC
Labels: bug

**Comment by hoshsadiq** [comment] 2020-04-20 15:46
It doesn't. By the way, since this issue is closed, would you like me to move this into a new issue?

```
$ ratbagctl warbling-mara info
warbling-mara - Logitech USB Receiver
             Model: usb:046d:c531:0
 Number of Buttons: 13
    Number of Leds: 0
Number of Profiles: 5
<clipped>
Profile 2: (active)
  Name: Profile 3
  Report Rate: 125Hz
  Resolutions:
    0: 475x475dpi (active)
    1: 1175x1175dpi
    2: 2350x2350dpi
    3: 3050x3050dpi
    4: 3775x3775dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to UNKNOWN
  Button: 6 is mapped to macro 'None'
  Button: 7 is mapped to 'battery-level'
  Button: 8 is mapped to 'resolution-down'
  Button: 9 is mapped to 'resolution-up'
  Button: 10 is mapped to 'profile-cycle-up'
  Button: 11 is mapped to 'wheel-left'
  Button: 12 is mapped to 'wheel-right'
<clipped>
```

**Comment by FFY00** [comment] 2020-04-21 16:48
Update to the latest kernel, IIRC there was a bug that has already been fixed.

**Comment by mrwiwi** [comment] 2020-04-21 16:51
> Update to the latest kernel, IIRC there was a bug that has already been fixed.

I'm on 5.7 RC1, I will try !

**Comment by mrwiwi** [comment] 2020-05-08 10:54
Do we have a fix if on latest ubuntu / popos 20.04 without going to upstream kernel ?

**Comment by calvertdw** [comment] 2020-05-22 04:28
I am on Linux 5.6.13-arch1-1 and libratbag version 0.14 and this is simple macros are still not working for me.

**Comment by FFY00** [comment] 2020-05-22 04:31
Only simple keybinds are supported for now. Complex macro support is planned.

**Comment by calvertdw** [comment] 2020-05-22 04:35
Here is my setup. Hitting button 6 or any button does not type a 'T'.
```
$ ratbagctl bellowing-paca button 6 action set macro KEY_T
$ ratbagctl bellowing-paca button 6 action get
Button: 6 is mapped to macro '↕T'
$ ratbagctl bellowing-paca info
bellowing-paca - Logitech USB Receiver
             Model: usb:046d:c531:0
 Number of Buttons: 13
    Number of Leds: 0
Number of Profiles: 5
Profile 0: (active)
  Name: Home Default
  Report Rate: 1000Hz
  Resolutions:
    0: 750x750dpi (active)
    1: <disabled>
    2: <disabled>
    3: <disabled>
    4: <disabled>
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to 'battery-level'
  Button: 6 is mapped to macro '↕T'
  Button: 7 is mapped to 'battery-level'
  Button: 8 is mapped to 'battery-level'
  Button: 9 is mapped to 'battery-level'
  Button: 10 is mapped to 'battery-level'
  Button: 11 is mapped to 'battery-level'
  Button: 12 is mapped to 'battery-level'
Profile 1: (disabled)
Profile 2: (disabled)
Profile 3: (disabled)
Profile 4: (disabled)
```

**Comment by calvertdw** [comment] 2020-05-22 04:39
Using the dbus monitor I do get an error at the end:
```
error time=1590122304.525863 sender=:1.101 -> destination=:1.438 error_name=org.freedesktop.DBus.Error.UnknownMethod reply_serial=489
   string "Unknown method Commit or interface org.freedesktop.ratbag1.Device."
```

**Comment by FFY00** [comment] 2020-05-22 04:40
That seems weird, can you open a new issue?

**Comment by calvertdw** [comment] 2020-05-24 03:37
Done: https://github.com/libratbag/libratbag/issues/991
